// The kernels ship inside the library: this emits one table of (name, source)
// per directory, read straight from the .loom files the generators write. It
// replaces host/native_sources.h (16k committed lines) and the block_sources.h
// that scripts/build_common.sh used to generate with shell.
use std::fmt::Write as _;
use std::path::Path;

fn table(root: &Path, directory: &str, name: &str) -> String {
    let path = root.join(directory);
    println!("cargo:rerun-if-changed={}", path.display());
    let mut entries: Vec<_> = std::fs::read_dir(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()))
        .map(|entry| entry.expect("readable directory entry").path())
        .filter(|entry| entry.extension().is_some_and(|e| e == "loom"))
        .collect();
    entries.sort();
    let mut text = format!(
        "/// Every kernel in `{directory}/`, embedded at build time.\n\
         pub static {name}: &[(&str, &str)] = &[\n"
    );
    for entry in entries {
        println!("cargo:rerun-if-changed={}", entry.display());
        let stem = entry.file_stem().expect("a .loom file has a stem").to_string_lossy();
        writeln!(text, "    ({stem:?}, include_str!({:?})),", entry.display())
            .expect("writing to a String cannot fail");
    }
    text.push_str("];\n\n");
    text
}

/// Cargo does not propagate a dependency's link arguments, so every package
/// that produces a binary or a test repeats the runtime rpath the `hrx` crate
/// sets for itself. Without it a `cargo test` cannot find libhrx.so.0.
fn runtime_rpath(root: &Path) {
    let runtime = std::env::var("KREA2_RUNTIME")
        .unwrap_or_else(|_| root.join("build/runtime").to_string_lossy().into_owned());
    println!("cargo:rerun-if-env-changed=KREA2_RUNTIME");
    println!("cargo:rustc-link-arg=-Wl,-rpath,{runtime}");
    println!("cargo:rustc-link-arg=-Wl,-rpath,$ORIGIN/runtime");
}

fn main() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("the crate sits in the repository")
        .to_path_buf();
    runtime_rpath(&root);
    let mut text = String::from("// Generated by crates/loom/build.rs.\n\n");
    text.push_str(&table(&root, "kernels/native", "AUXILIARY"));
    text.push_str(&table(&root, "kernels", "BLOCK"));
    let out =
        Path::new(&std::env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("sources.rs");
    std::fs::write(&out, text).expect("writing the source table");
}
