"""Derive kernels/attention_gqa_f16_wmma.loom (head dim 128, grouped-query heads, one
sequence, f16 out) from dinov3-loom's attention_online_f16_wmma.loom by anchored
substitution. Every anchor is checked and named on failure."""
import re
import sys
from pathlib import Path

SRC = Path.home() / "code/dinov3-loom/kernels/attention_online_f16_wmma.loom"
OUT = Path(__file__).resolve().parent.parent / "kernels/attention_gqa_f16_wmma.loom"

s = SRC.read_text()
def sub(name, a, b, count=1):
    global s
    if a not in s:
        sys.exit(f"anchor missing: {name}\n{a[:120]}")
    s = s.replace(a, b, count)
def cut(name, start, end):
    if start not in s or end not in s:
        sys.exit(f"cut markers missing: {name} start={start in s} end={end in s}")
    return s[s.index(start):s.index(end)]

s = s.replace("dinov3_attention_online_f16_wmma", "krea2_attention_gqa_f16_wmma").replace("dinov3.attention_online_f16_wmma", "krea2.attention_gqa_f16_wmma").replace("dinov3_attention_online_gfx11", "krea2_attention_gqa_gfx11")
s = s[s.index("amdgpu.target"):]
HEADER = """// Online-softmax attention for Krea 2: one wave32 per (16 query rows, head), head
// dim 128, grouped-query heads (kv head = head / kv_groups), a single sequence.
//
// Ported from dinov3-loom's attention_online_f16_wmma (itself from hrx-demos'
// ideogram4 kernel): K and V fragments load straight from global, K's transpose
// is a strided view, the workgroup is one wave, and the only LDS is 512 bytes to
// turn the f32 score fragment into an f16 lhs for P*V plus the 8 KB result stage.
// Running max and sum stay in registers, split across the two lane groups that own
// different fragment rows; eight 16x16 accumulators hold the 128 output channels.
//
// q is f16 [tokens][q_stride] (the 48 heads x 128); k and v are f16
// [tokens][kv_stride] (the 12 kv heads x 128). Their buffers need 16 rows of
// headroom (token_capacity >= tokens + 16): the overhanging rows are masked.
// Output is f16 [tokens][q_stride] at this head's 128 channels.
//
// GENERATED by tools/gen_attention.py; edit the generator.
"""
s = HEADER + s
NS = "krea2.attention_gqa_f16_wmma"
sub("hidden_size decl", f"config.decl @{NS}.hidden_size : %value: index where [range(%value, 64, 8192), mul(%value, 64)]\n",
    f"config.decl @{NS}.kv_stride : %value: index where [range(%value, 128, 32768), mul(%value, 128)]\n\nconfig.decl @{NS}.kv_groups : %value: index where [range(%value, 1, 64)]\n")
sub("qkv_stride decl", f"config.decl @{NS}.qkv_stride : %value: index where [range(%value, 64, 32768), mul(%value, 64)]",
    f"config.decl @{NS}.q_stride : %value: index where [range(%value, 128, 32768), mul(%value, 128)]")
s = s.replace(f"@{NS}.tokens_per_image", f"@{NS}.tokens")
s = s.replace(f"config.decl @{NS}.max_images : %value: index where [range(%value, 1, 1024)]\n", "")
s = s.replace(f"config.decl @{NS}.tokens : %value: index where [range(%value, 16, 8192)]",
              f"config.decl @{NS}.tokens : %value: index where [range(%value, 16, 65536)]")
sub("launch config", """  %images = index.div %token_count, %tokens_per_image0 : index
  %tiles = index.mul %images, %tiles_per_image : index
  kernel.launch.config workgroups(%tiles, %head_count, %c1) workgroup_size(%c32, %c1, %c1) : index""",
    """  kernel.launch.config workgroups(%tiles_per_image, %head_count, %c1) workgroup_size(%c32, %c1, %c1) : index""")
sub("config gets", f"  %hidden_size0 = config.get @{NS}.hidden_size : index\n  %qkv_stride0 = config.get @{NS}.qkv_stride : index\n",
    f"  %q_stride0 = config.get @{NS}.q_stride : index\n  %kv_stride0 = config.get @{NS}.kv_stride : index\n  %kv_groups = config.get @{NS}.kv_groups : index\n")
sub("constants", "  %c64 = index.constant 64 : index\n", "  %c64 = index.constant 64 : index\n  %c80 = index.constant 80 : index\n  %c96 = index.constant 96 : index\n  %c112 = index.constant 112 : index\n  %c128 = index.constant 128 : index\n")
sub("head limit", "  %head_limit = index.div %hidden_size0, %c64 : index\n  %head = index.rem %head_raw, %head_limit : index\n",
    "  %head_limit = index.div %q_stride0, %c128 : index\n  %head = index.rem %head_raw, %head_limit : index\n  %kv_head_limit = index.div %kv_stride0, %c128 : index\n  %kv_head0 = index.div %head, %kv_groups : index\n  %kv_head = index.rem %kv_head0, %kv_head_limit : index\n")
sub("image machinery", """  %image_raw = index.div %tile_id, %tiles_per_image : index
  %image_limit = config.get @krea2.attention_gqa_f16_wmma.max_images : index
  %image = index.rem %image_raw, %image_limit : index
  %tile_in_image = index.rem %tile_id, %tiles_per_image : index
  %image_base = index.mul %image, %tokens_per_image0 : index
""", """  %tile_in_image = index.rem %tile_id, %tiles_per_image : index
  %image_base = index.add %c0, %c0 : index
""")
sub("head base", "  %head_base0 = index.mul %head, %c64 : index\n  %channel_limit = index.sub %hidden_size0, %c64 : index\n",
    "  %head_base0 = index.mul %head, %c128 : index\n  %kv_base0 = index.mul %kv_head, %c128 : index\n")
sub("transposed layout", "  %transposed_layout = encoding.layout.strided [1, %qkv_stride0] : encoding<layout>\n", "")
s = "\n".join(
    (l.replace("%qkv_stride0", "%q_stride0") if ("%q_view" in l or "%q_aligned" in l) else
     l.replace("%qkv_stride0", "%kv_stride0") if ("%k_transposed" in l or "%v_view" in l or "%k_aligned" in l or "%v_aligned" in l) else l)
    for l in s.split("\n"))
sub("k view", "  %k_transposed = buffer.view %k_aligned[%c0_offset] : buffer -> view<[%kv_stride0]x[%padded_tokens]xf16, %transposed_layout>\n",
    "  %k_view = buffer.view %k_aligned[%c0_offset] : buffer -> view<[%padded_tokens]x[%kv_stride0]xf16>\n")
sub("v view", "  %v_view = buffer.view %v_aligned[%c0_offset] : buffer -> view<[%padded_tokens]x[%kv_stride0]xf16>\n",
    "  // V arrives transposed, [kv_stride][token_capacity], so a lane's 16 keys of one\n  // channel are contiguous; keys past the sequence are zero there.\n  %vt_view = buffer.view %v_aligned[%c0_offset] : buffer -> view<[%kv_stride0]x[%padded_tokens]xf16>\n")
sub("hoist q", "  %init = vector.fragment<init> %zero_acc shape [%m, %n] : vector<8xf32>\n",
    "  %init = vector.fragment<init> %zero_acc shape [%m, %n] : vector<8xf32>\n  // The 16 query rows' eight lhs fragments, loaded once.\n"
    + "".join(f"  %q_channel{j} = index.add %head_base0, %c{16*j} : index\n  %lhs{j} = vector.fragment.load<lhs> %q_view[%query_origin0, %q_channel{j}] shape [%m, %k_frag] : view<[%padded_tokens]x[%q_stride0]xf16> -> vector<16xf16>\n" if j else "  %q_channel0 = index.add %head_base0, %c0 : index\n  %lhs0 = vector.fragment.load<lhs> %q_view[%query_origin0, %q_channel0] shape [%m, %k_frag] : view<[%padded_tokens]x[%q_stride0]xf16> -> vector<16xf16>\n" for j in range(8)))
sub("out view", "  %out_view = buffer.view %out_global[%c0_offset] : buffer -> view<[%token_count]x[%hidden_size0]xf32>\n",
    "  %out_view = buffer.view %out_global[%c0_offset] : buffer -> view<[%token_count]x[%q_stride0]xf16>\n")
sub("result bytes", "  %result_bytes = index.constant 4096 : offset\n", "  %result_bytes = index.constant 8192 : offset\n")
s = s.replace("view<16x64xf32>", "view<16x128xf32>")
sub("final results", "%final0, %final1, %final2, %final3 = scf.for", "%final0, %final1, %final2, %final3, %final4, %final5, %final6, %final7 = scf.for")
sub("loop header", "%acc2 = %init : vector<8xf32>, %acc3 = %init : vector<8xf32>) -> (vector<8xf32>, vector<8xf32>, vector<8xf32>, vector<8xf32>, vector<8xf32>, vector<8xf32>, vector<8xf32>, vector<8xf32>) {",
    "%acc2 = %init : vector<8xf32>, %acc3 = %init : vector<8xf32>, %acc4 = %init : vector<8xf32>, %acc5 = %init : vector<8xf32>, %acc6 = %init : vector<8xf32>, %acc7 = %init : vector<8xf32>) -> (" + ", ".join(["vector<8xf32>"] * 12) + ") {")
sub("qk loop", """    %raw_scores = scf.for %head_tile = [%c0 to %c64 step %c16](%qk = %init : vector<8xf32>) -> (vector<8xf32>) unroll {
      %channel = index.add %head_base0, %head_tile : index
      %lhs = vector.fragment.load<lhs> %q_view[%query_origin0, %channel] shape [%m, %k_frag] : view<[%padded_tokens]x[%q_stride0]xf16> -> vector<16xf16>
      %rhs = vector.fragment.load<rhs> %k_transposed[%channel, %key_origin0] shape [%k_frag, %n] : view<[%kv_stride0]x[%padded_tokens]xf16, %transposed_layout> -> vector<16xf16>
      %next = vector.mma %lhs, %rhs, %qk : vector<16xf16>, vector<16xf16>, vector<8xf32>
      scf.yield %next : vector<8xf32>
    }""",
    """    // K as the rhs operand, assembled by hand: lane l holds key (l mod 16) with 16
    // contiguous channels, which is K's own row layout -- two 16-byte loads per
    // fragment instead of the transposed view's sixteen 2-byte ones. The eight
    // 16-channel steps are written out so each uses its hoisted query fragment.
    %key_row = index.add %key_origin0, %lane_column : index
    %k_data0 = vector.load %k_view[%key_row, %kv_base0] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
    %rhs0 = vector.fragment<rhs> %k_data0 shape [%k_frag, %n] : vector<16xf16>
    %qk0 = vector.mma %lhs0, %rhs0, %init : vector<16xf16>, vector<16xf16>, vector<8xf32>
    %kv_channel1 = index.add %kv_base0, %c16 : index
    %k_data1 = vector.load %k_view[%key_row, %kv_channel1] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
    %rhs1 = vector.fragment<rhs> %k_data1 shape [%k_frag, %n] : vector<16xf16>
    %qk1 = vector.mma %lhs1, %rhs1, %qk0 : vector<16xf16>, vector<16xf16>, vector<8xf32>
    %kv_channel2 = index.add %kv_base0, %c32 : index
    %k_data2 = vector.load %k_view[%key_row, %kv_channel2] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
    %rhs2 = vector.fragment<rhs> %k_data2 shape [%k_frag, %n] : vector<16xf16>
    %qk2 = vector.mma %lhs2, %rhs2, %qk1 : vector<16xf16>, vector<16xf16>, vector<8xf32>
    %kv_channel3 = index.add %kv_base0, %c48 : index
    %k_data3 = vector.load %k_view[%key_row, %kv_channel3] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
    %rhs3 = vector.fragment<rhs> %k_data3 shape [%k_frag, %n] : vector<16xf16>
    %qk3 = vector.mma %lhs3, %rhs3, %qk2 : vector<16xf16>, vector<16xf16>, vector<8xf32>
    %kv_channel4 = index.add %kv_base0, %c64 : index
    %k_data4 = vector.load %k_view[%key_row, %kv_channel4] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
    %rhs4 = vector.fragment<rhs> %k_data4 shape [%k_frag, %n] : vector<16xf16>
    %qk4 = vector.mma %lhs4, %rhs4, %qk3 : vector<16xf16>, vector<16xf16>, vector<8xf32>
    %kv_channel5 = index.add %kv_base0, %c80 : index
    %k_data5 = vector.load %k_view[%key_row, %kv_channel5] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
    %rhs5 = vector.fragment<rhs> %k_data5 shape [%k_frag, %n] : vector<16xf16>
    %qk5 = vector.mma %lhs5, %rhs5, %qk4 : vector<16xf16>, vector<16xf16>, vector<8xf32>
    %kv_channel6 = index.add %kv_base0, %c96 : index
    %k_data6 = vector.load %k_view[%key_row, %kv_channel6] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
    %rhs6 = vector.fragment<rhs> %k_data6 shape [%k_frag, %n] : vector<16xf16>
    %qk6 = vector.mma %lhs6, %rhs6, %qk5 : vector<16xf16>, vector<16xf16>, vector<8xf32>
    %kv_channel7 = index.add %kv_base0, %c112 : index
    %k_data7 = vector.load %k_view[%key_row, %kv_channel7] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
    %rhs7 = vector.fragment<rhs> %k_data7 shape [%k_frag, %n] : vector<16xf16>
    %raw_scores = vector.mma %lhs7, %rhs7, %qk6 : vector<16xf16>, vector<16xf16>, vector<8xf32>""")
old_v = cut("v block", "    %channel0 = index.add %head_base0, %c0 : index", "    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)\n    scf.yield %next_max_even")
new_v = "".join((f"    %channel{j} = index.add %kv_base0, %c{16*j} : index\n" if j else "    %channel0 = index.add %kv_base0, %c0 : index\n") for j in range(8))
new_v += "".join(f"    %vt_row{j} = index.add %channel{j}, %lane_column : index\n" for j in range(8))
new_v += "".join(f"    %v_data{j} = vector.load %vt_view[%vt_row{j}, %key_origin0] : view<[%kv_stride0]x[%padded_tokens]xf16> -> vector<16xf16>\n" for j in range(8))
new_v += "".join(f"    %v{j} = vector.fragment<rhs> %v_data{j} shape [%k_frag, %n] : vector<16xf16>\n" for j in range(8))
new_v += "".join(f"    %rescaled{j} = vector.mulf<reassoc|nnan|ninf|nsz|contract> %acc{j}, %selected_old_scale : vector<8xf32>\n" for j in range(8))
new_v += "".join(f"    %next{j} = vector.mma %probability, %v{j}, %rescaled{j} : vector<16xf16>, vector<16xf16>, vector<8xf32>\n" for j in range(8))
s = s.replace(old_v, new_v, 1)
sub("loop yield", "    scf.yield %next_max_even, %next_sum_even, %next_max_odd, %next_sum_odd, %next0, %next1, %next2, %next3 : vector<8xf32>, vector<8xf32>, vector<8xf32>, vector<8xf32>, vector<8xf32>, vector<8xf32>, vector<8xf32>, vector<8xf32>\n",
    "    scf.yield %next_max_even, %next_sum_even, %next_max_odd, %next_sum_odd, " + ", ".join(f"%next{j}" for j in range(8)) + " : " + ", ".join(["vector<8xf32>"] * 12) + "\n")
old_out = cut("out block", "  %out0 = vector.divf", "  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)\n\n  // 16 rows x 64")
new_out = "".join(f"  %out{j} = vector.divf<nnan|ninf|nsz|arcp> %final{j}, %selected_sum : vector<8xf32>\n" for j in range(8))
new_out += "".join((f"  vector.fragment.store<result> %out{j}, %result_view[%c0, %c{16*j}] shape [%m, %n] : vector<8xf32>, view<16x128xf32>\n" if j else "  vector.fragment.store<result> %out0, %result_view[%c0, %c0] shape [%m, %n] : vector<8xf32>, view<16x128xf32>\n") for j in range(8))
s = s.replace(old_out, new_out, 1)
sub("epilogue header", "  // 16 rows x 64 channels is 256 vector4s over 32 lanes: eight each, with the\n  // rows that ran past this image's tokens dropped.\n  %hidden_vector_limit = index.sub %hidden_size0, %c4 : index\n  scf.for %step = [%c0 to %c8 step %c1] {",
    "  // 16 rows x 128 channels is 512 vector4s over 32 lanes: sixteen each, with the\n  // rows that ran past the sequence dropped.\n  %hidden_vector_limit = index.sub %q_stride0, %c4 : index\n  scf.for %step = [%c0 to %c16 step %c1] {")
sub("epilogue slot", "    %row = index.div %slot, %c16 : index\n    %column_group = index.rem %slot, %c16 : index\n",
    "    %row = index.div %slot, %c32 : index\n    %column_group = index.rem %slot, %c32 : index\n")
sub("epilogue store", "      %values = vector.load %result_view[%row, %column] : view<16x128xf32> -> vector<4xf32>\n      %out_column0 = index.add %head_base0, %column : index\n      %out_column = index.assume %out_column0 [le(%out_column0, %hidden_vector_limit)] : index\n      vector.store %values, %out_view[%global_row, %out_column] : vector<4xf32>, view<[%token_count]x[%hidden_size0]xf32>\n",
    "      %values = vector.load %result_view[%row, %column] : view<16x128xf32> -> vector<4xf32>\n      %halves = vector.fptrunc %values : vector<4xf32> to vector<4xf16>\n      %out_column0 = index.add %head_base0, %column : index\n      %out_column = index.assume %out_column0 [le(%out_column0, %hidden_vector_limit)] : index\n      vector.store %halves, %out_view[%global_row, %out_column] : vector<4xf16>, view<[%token_count]x[%q_stride0]xf16>\n")
left = [l for l in s.split("\n") if "%hidden_size0" in l or "%qkv_stride0" in l or "max_images" in l or "%k_transposed" in l or "%v_view" in l]
if left:
    sys.exit("leftover names:\n" + "\n".join(left[:5]))
OUT.write_text(s)
print("wrote", OUT)
