"""kernels/attention_gqa_lds_f16_wmma.loom: GQA attention with K/V tiles staged in LDS.

One workgroup of four waves per (16 query rows, key-value head): wave w is query head
kv_head*4 + w. Per 16-key tile the workgroup loads the K tile [16][128] and the V tile
[16][128] cooperatively and coalesced (each lane 32 contiguous bytes), stores them in
LDS, and all four waves take their operands from there: K's rhs by hand (lane = key,
16 contiguous channels), V's rhs as dense fragment loads from the tile rows. The online softmax,
running statistics and epilogue are the tested 16-key kernel's."""
import sys
from pathlib import Path

PREFETCH = "--prefetch" in sys.argv

ROOT = Path(__file__).resolve().parent.parent
STEM = "attention_gqa_ldsp_f16_wmma" if PREFETCH else "attention_gqa_lds_f16_wmma"
OUT = ROOT / f"kernels/{STEM}.loom"
NS, SYM = "krea2." + STEM, "krea2_" + STEM
ROW = 136   # LDS row length in halves for a 128-channel tile (272-byte rows)


K = f"""// GQA attention for Krea 2 with K/V tiles staged in LDS: one workgroup of four waves
// per (16 query rows, key-value head); wave w owns query head kv_head*4 + w. Each
// 16-key tile of K and V is loaded once, coalesced (a lane reads 32 contiguous bytes),
// into LDS and serves all four heads; K's rhs fragments are assembled from the LDS rows
// (lane = key, 16 contiguous channels), V's as dense rhs loads from the tile rows (the tile's [key][channel] layout is the rhs' logical [k][n]). Online
// softmax with running max and sum per lane group, eight accumulators for the 128
// output channels, f16 out. q [tokens][q_stride], k and v [tokens][kv_stride] (natural
// layout, no transpose needed), token_capacity >= tokens + 16 with zero headroom.
//
// GENERATED by tools/gen_attention_lds.py; edit the generator.
amdgpu.target<gfx11-generic> @{SYM}_gfx11 {{subgroup_size = 32}}

config.decl @{NS}.q_stride : %value: index where [range(%value, 128, 32768), mul(%value, 128)]

config.decl @{NS}.kv_stride : %value: index where [range(%value, 128, 32768), mul(%value, 128)]

config.decl @{NS}.out_stride : %value: index where [range(%value, 128, 32768), mul(%value, 128)]

config.decl @{NS}.tokens : %value: index where [range(%value, 16, 65536)]

config.decl @{NS}.token_capacity : %value: index where [range(%value, 32, 1048576), mul(%value, 16)]

config.decl @{NS}.scale : f32

kernel.def target(@{SYM}_gfx11) export("{SYM}") @{SYM}(%token_count: index, %kv_head_count: index) {{
  %c1 = index.constant 1 : index
  %c15 = index.constant 15 : index
  %c16 = index.constant 16 : index
  %c128 = index.constant 128 : index
  %tokens0 = config.get @{NS}.tokens : index
  %rounded = index.add %tokens0, %c15 : index
  %tiles = index.div %rounded, %c16 : index
  kernel.launch.config workgroups(%tiles, %kv_head_count, %c1) workgroup_size(%c128, %c1, %c1) : index
}} launch(%token_count: index, %q: buffer, %k: buffer, %v: buffer, %out: buffer) {{
  %q_stride0 = config.get @{NS}.q_stride : index
  %kv_stride0 = config.get @{NS}.kv_stride : index
  %out_stride0 = config.get @{NS}.out_stride : index
  %tokens0 = config.get @{NS}.tokens : index
  %padded_tokens = config.get @{NS}.token_capacity : index
  %scale = config.get @{NS}.scale : f32
  %c0 = index.constant 0 : index
  %c1 = index.constant 1 : index
  %c2 = index.constant 2 : index
  %c3 = index.constant 3 : index
  %c4 = index.constant 4 : index
  %c5 = index.constant 5 : index
  %c6 = index.constant 6 : index
  %c7 = index.constant 7 : index
  %c8 = index.constant 8 : index
  %c15 = index.constant 15 : index
  %c16 = index.constant 16 : index
  %c32 = index.constant 32 : index
  %c48 = index.constant 48 : index
  %c64 = index.constant 64 : index
  %c80 = index.constant 80 : index
  %c96 = index.constant 96 : index
  %c112 = index.constant 112 : index
  %c128 = index.constant 128 : index
  %c{ROW} = index.constant {ROW} : index
  %c0_offset = index.constant 0 : offset
  %k_tile_offset = index.constant 0 : offset
  %v_tile_offset = index.constant {16 * ROW * 2} : offset
  %scratch_offset = index.constant {2 * 16 * ROW * 2} : offset
  %result_offset = index.constant {2 * 16 * ROW * 2 + 4 * 512} : offset
  %lds_bytes = index.constant {2 * 16 * ROW * 2 + 4 * 512 + 4 * 1024} : offset
  %m = index.constant 16 : index
  %n = index.constant 16 : index
  %k_frag = index.constant 16 : index
  %zero_f32 = scalar.constant 0.0 : f32
  %negative_large = scalar.constant -1000000000.0 : f32
  %zero_acc = vector.constant 0.0 : vector<8xf32>
  %zero_vector = vector.splat %zero_f32 : vector<8xf32>
  %negative_vector = vector.splat %negative_large : vector<8xf32>
  %scale_vector = vector.splat %scale : vector<8xf32>

  %tile_id = kernel.workgroup.id<x> : index
  %kv_head_raw = kernel.workgroup.id<y> : index
  %kv_head_limit = index.div %kv_stride0, %c128 : index
  %kv_head = index.rem %kv_head_raw, %kv_head_limit : index
  %workitem = kernel.workitem.id<x> : index
  %wave0 = kernel.subgroup.id : index
  %wave = index.assume %wave0 [range(%wave0, 0, 3)] : index
  %lane = kernel.subgroup.lane.id : index
  %lane_column = index.rem %lane, %c16 : index
  %lane_group = index.div %lane, %c16 : index
  %lane_group_even = index.cmp eq, %lane_group, %c0 : index
  // this wave's query head, and its channels in q and out
  %head_limit = index.div %out_stride0, %c128 : index
  %head0 = index.mul %kv_head, %c4 : index
  %head1 = index.add %head0, %wave : index
  %head = index.rem %head1, %head_limit : index
  %head_base0 = index.mul %head, %c128 : index
  %kv_base0 = index.mul %kv_head, %c128 : index
  %rounded = index.add %tokens0, %c15 : index
  %tiles_per_image = index.div %rounded, %c16 : index
  %tile_in_image = index.rem %tile_id, %tiles_per_image : index
  %query_origin0 = index.mul %tile_in_image, %c16 : index
  %tile_origin_limit = index.sub %padded_tokens, %c16 : index

  %q_global = buffer.assume.memory_space<global> %q : buffer
  %k_global = buffer.assume.memory_space<global> %k : buffer
  %v_global = buffer.assume.memory_space<global> %v : buffer
  %out_global = buffer.assume.memory_space<global> %out : buffer
  %q_view = buffer.view %q_global[%c0_offset] : buffer -> view<[%padded_tokens]x[%q_stride0]xf16>
  %k_view = buffer.view %k_global[%c0_offset] : buffer -> view<[%padded_tokens]x[%kv_stride0]xf16>
  %v_view = buffer.view %v_global[%c0_offset] : buffer -> view<[%padded_tokens]x[%kv_stride0]xf16>
  %out_view = buffer.view %out_global[%c0_offset] : buffer -> view<[%token_count]x[%out_stride0]xf16>

  %lds = buffer.alloca<workgroup> align(16) %lds_bytes : buffer
  // K and V tiles: 16 keys x 128 channels, rows padded to {ROW} halves
  %k_tile = buffer.view %lds[%k_tile_offset] : buffer -> view<16x{ROW}xf16>
  %v_tile = buffer.view %lds[%v_tile_offset] : buffer -> view<16x{ROW}xf16>
  %wave_scratch_bytes = index.constant 512 : offset
  %wave_scratch_offset0 = index.scale %wave, %wave_scratch_bytes : index, offset -> offset
  %wave_scratch_offset = index.add %scratch_offset, %wave_scratch_offset0 : offset
  %scratch_view = buffer.view %lds[%wave_scratch_offset] : buffer -> view<16x16xf16>
  %wave_result_bytes = index.constant 1024 : offset
  %wave_result_offset0 = index.scale %wave, %wave_result_bytes : index, offset -> offset
  %wave_result_offset = index.add %result_offset, %wave_result_offset0 : offset
  %result_view = buffer.view %lds[%wave_result_offset] : buffer -> view<16x16xf32>

  // cooperative staging map: lane -> key workitem/8, 16-channel chunk (workitem%8)*16
  %st_key = index.div %workitem, %c8 : index
  %st_chunk0 = index.rem %workitem, %c8 : index
  %st_chunk = index.mul %st_chunk0, %c16 : index
  %st_col0 = index.add %kv_base0, %st_chunk : index
  %kv_col_limit = index.sub %kv_stride0, %c16 : index
  %st_col = index.assume %st_col0 [le(%st_col0, %kv_col_limit), mul(%st_col0, 16)] : index
  %init = vector.fragment<init> %zero_acc shape [%m, %n] : vector<8xf32>
  %key_tile_count = index.add %tiles_per_image, %c0 : index

  %zero_chunk = vector.constant 0.0 : vector<16xf16>
"""
if PREFETCH:
    K += f"""  // The first tile's chunks, loaded before the loop; every iteration stores the chunks
  // it was handed, barriers, loads the next tile's while the WMMAs run.
  %st_row_first0 = index.add %c0, %st_key : index
  %st_row_first = index.assume %st_row_first0 [lt(%st_row_first0, %padded_tokens)] : index
  %k_first = vector.load %k_view[%st_row_first, %st_col] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
  %v_first = vector.load %v_view[%st_row_first, %st_col] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
  %final_max_even, %final_sum_even, %final_max_odd, %final_sum_odd, %final0, %final1, %final2, %final3, %final4, %final5, %final6, %final7, %k_last, %v_last = scf.for %key_tile = [%c0 to %key_tile_count step %c1](%max_even = %negative_vector : vector<8xf32>, %sum_even = %zero_vector : vector<8xf32>, %max_odd = %negative_vector : vector<8xf32>, %sum_odd = %zero_vector : vector<8xf32>, %acc0 = %init : vector<8xf32>, %acc1 = %init : vector<8xf32>, %acc2 = %init : vector<8xf32>, %acc3 = %init : vector<8xf32>, %acc4 = %init : vector<8xf32>, %acc5 = %init : vector<8xf32>, %acc6 = %init : vector<8xf32>, %acc7 = %init : vector<8xf32>, %k_cur = %k_first : vector<16xf16>, %v_cur = %v_first : vector<16xf16>) -> ({", ".join(["vector<8xf32>"] * 12)}, vector<16xf16>, vector<16xf16>) {{
    %key_origin1 = index.mul %key_tile, %c16 : index
    %key_origin0 = index.assume %key_origin1 [le(%key_origin1, %tile_origin_limit), mul(%key_origin1, 16)] : index
    vector.store %k_cur, %k_tile[%st_key, %st_chunk] : vector<16xf16>, view<16x{ROW}xf16>
    vector.store %v_cur, %v_tile[%st_key, %st_chunk] : vector<16xf16>, view<16x{ROW}xf16>
    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)
    // next tile's chunks (zero past the last tile)
    %next_tile = index.add %key_tile, %c1 : index
    %has_next = index.cmp ult, %next_tile, %key_tile_count : index
    %next_origin1 = index.mul %next_tile, %c16 : index
    %next_origin2 = scf.select %has_next, %next_origin1, %c0 : index
    %next_origin = index.assume %next_origin2 [le(%next_origin2, %tile_origin_limit), mul(%next_origin2, 16)] : index
    %st_row_next0 = index.add %next_origin, %st_key : index
    %st_row_next = index.assume %st_row_next0 [lt(%st_row_next0, %padded_tokens)] : index
    %k_next = scf.if %has_next -> (vector<16xf16>) {{
      %kl = vector.load %k_view[%st_row_next, %st_col] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
      scf.yield %kl : vector<16xf16>
    }} else {{
      scf.yield %zero_chunk : vector<16xf16>
    }}
    %v_next = scf.if %has_next -> (vector<16xf16>) {{
      %vl = vector.load %v_view[%st_row_next, %st_col] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
      scf.yield %vl : vector<16xf16>
    }} else {{
      scf.yield %zero_chunk : vector<16xf16>
    }}
"""
else:
    K += f"""  %final_max_even, %final_sum_even, %final_max_odd, %final_sum_odd, %final0, %final1, %final2, %final3, %final4, %final5, %final6, %final7 = scf.for %key_tile = [%c0 to %key_tile_count step %c1](%max_even = %negative_vector : vector<8xf32>, %sum_even = %zero_vector : vector<8xf32>, %max_odd = %negative_vector : vector<8xf32>, %sum_odd = %zero_vector : vector<8xf32>, %acc0 = %init : vector<8xf32>, %acc1 = %init : vector<8xf32>, %acc2 = %init : vector<8xf32>, %acc3 = %init : vector<8xf32>, %acc4 = %init : vector<8xf32>, %acc5 = %init : vector<8xf32>, %acc6 = %init : vector<8xf32>, %acc7 = %init : vector<8xf32>) -> ({", ".join(["vector<8xf32>"] * 12)}) {{
    %key_origin1 = index.mul %key_tile, %c16 : index
    %key_origin0 = index.assume %key_origin1 [le(%key_origin1, %tile_origin_limit), mul(%key_origin1, 16)] : index
    // stage K and V tiles (rows past the sequence are zero headroom)
    %st_row0 = index.add %key_origin0, %st_key : index
    %st_row = index.assume %st_row0 [lt(%st_row0, %padded_tokens)] : index
    %k_chunk = vector.load %k_view[%st_row, %st_col] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
    %v_chunk = vector.load %v_view[%st_row, %st_col] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
    vector.store %k_chunk, %k_tile[%st_key, %st_chunk] : vector<16xf16>, view<16x{ROW}xf16>
    vector.store %v_chunk, %v_tile[%st_key, %st_chunk] : vector<16xf16>, view<16x{ROW}xf16>
    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)
"""
K += f"""
    %local_key = index.add %key_origin0, %lane_column : index
    %key_valid = index.cmp ult, %local_key, %tokens0 : index
"""
# scores: 8 channel steps, q fragment from global, k rhs from the LDS row (lane = key)
prev = "%init"
for c in range(8):
    K += (f"    %q_channel{c} = index.add %head_base0, %c{16*c} : index\n" if c else "    %q_channel0 = index.add %head_base0, %c0 : index\n")
    K += f"    %lhs{c} = vector.fragment.load<lhs> %q_view[%query_origin0, %q_channel{c}] shape [%m, %k_frag] : view<[%padded_tokens]x[%q_stride0]xf16> -> vector<16xf16>\n"
    K += f"    %k_data{c} = vector.load %k_tile[%lane_column, %c{16*c}] : view<16x{ROW}xf16> -> vector<16xf16>\n" if c else f"    %k_data0 = vector.load %k_tile[%lane_column, %c0] : view<16x{ROW}xf16> -> vector<16xf16>\n"
    K += f"    %rhs{c} = vector.fragment<rhs> %k_data{c} shape [%k_frag, %n] : vector<16xf16>\n"
    out = "%raw_scores" if c == 7 else f"%qk{c}"
    K += f"    {out} = vector.mma %lhs{c}, %rhs{c}, {prev} : vector<16xf16>, vector<16xf16>, vector<8xf32>\n"
    prev = out
K += """    %scaled0 = vector.mulf<reassoc|nnan|ninf|nsz|contract> %raw_scores, %scale_vector : vector<8xf32>
    %scaled = scf.if %key_valid -> (vector<8xf32>) {
      scf.yield %scaled0 : vector<8xf32>
    } else {
      scf.yield %negative_vector : vector<8xf32>
    }
    %even_scores = scf.if %lane_group_even -> (vector<8xf32>) {
      scf.yield %scaled : vector<8xf32>
    } else {
      scf.yield %negative_vector : vector<8xf32>
    }
    %odd_scores = scf.if %lane_group_even -> (vector<8xf32>) {
      scf.yield %negative_vector : vector<8xf32>
    } else {
      scf.yield %scaled : vector<8xf32>
    }
    %tile_max_even = kernel.subgroup.reduce<maxnumf> %even_scores : vector<8xf32>
    %tile_max_odd = kernel.subgroup.reduce<maxnumf> %odd_scores : vector<8xf32>
    %next_max_even = vector.maxnumf %max_even, %tile_max_even : vector<8xf32>
    %next_max_odd = vector.maxnumf %max_odd, %tile_max_odd : vector<8xf32>
    %selected_max = scf.if %lane_group_even -> (vector<8xf32>) {
      scf.yield %next_max_even : vector<8xf32>
    } else {
      scf.yield %next_max_odd : vector<8xf32>
    }
    %delta = vector.subf<reassoc|nnan|ninf|nsz> %scaled, %selected_max : vector<8xf32>
    %raw_weight = vector.expf<afn> %delta : vector<8xf32>
    %weight = scf.if %key_valid -> (vector<8xf32>) {
      scf.yield %raw_weight : vector<8xf32>
    } else {
      scf.yield %zero_vector : vector<8xf32>
    }
    %even_weight = scf.if %lane_group_even -> (vector<8xf32>) {
      scf.yield %weight : vector<8xf32>
    } else {
      scf.yield %zero_vector : vector<8xf32>
    }
    %odd_weight = scf.if %lane_group_even -> (vector<8xf32>) {
      scf.yield %zero_vector : vector<8xf32>
    } else {
      scf.yield %weight : vector<8xf32>
    }
    %tile_sum_even = kernel.subgroup.reduce<addf> %even_weight : vector<8xf32>
    %tile_sum_odd = kernel.subgroup.reduce<addf> %odd_weight : vector<8xf32>
    %old_delta_even = vector.subf<reassoc|nnan|ninf|nsz> %max_even, %next_max_even : vector<8xf32>
    %old_delta_odd = vector.subf<reassoc|nnan|ninf|nsz> %max_odd, %next_max_odd : vector<8xf32>
    %old_scale_even = vector.expf<afn> %old_delta_even : vector<8xf32>
    %old_scale_odd = vector.expf<afn> %old_delta_odd : vector<8xf32>
    %scaled_sum_even = vector.mulf<reassoc|nnan|ninf|nsz|contract> %sum_even, %old_scale_even : vector<8xf32>
    %scaled_sum_odd = vector.mulf<reassoc|nnan|ninf|nsz|contract> %sum_odd, %old_scale_odd : vector<8xf32>
    %next_sum_even = vector.addf<reassoc|nnan|ninf|nsz> %scaled_sum_even, %tile_sum_even : vector<8xf32>
    %next_sum_odd = vector.addf<reassoc|nnan|ninf|nsz> %scaled_sum_odd, %tile_sum_odd : vector<8xf32>
    %selected_old_scale = scf.if %lane_group_even -> (vector<8xf32>) {
      scf.yield %old_scale_even : vector<8xf32>
    } else {
      scf.yield %old_scale_odd : vector<8xf32>
    }
    // the f32 weights become an f16 lhs through this wave's 512-byte scratch
    vector.fragment.store<result> %weight, %scratch_view[%c0, %c0] shape [%m, %n] : vector<8xf32>, view<16x16xf16>
    kernel.barrier<workgroup> scope(subgroup) ordering(acq_rel)
    %probability = vector.fragment.load<lhs> %scratch_view[%c0, %c0] shape [%m, %k_frag] : view<16x16xf16> -> vector<16xf16>
"""
for c in range(8):
    # B[k = key][n = channel] is the V tile's own row layout: a dense rhs load
    K += f"    %v{c} = vector.fragment.load<rhs> %v_tile[%c0, %c{16*c}] shape [%k_frag, %n] : view<16x{ROW}xf16> -> vector<16xf16>\n" if c else \
         f"    %v0 = vector.fragment.load<rhs> %v_tile[%c0, %c0] shape [%k_frag, %n] : view<16x{ROW}xf16> -> vector<16xf16>\n"
for c in range(8):
    K += f"    %rescaled{c} = vector.mulf<reassoc|nnan|ninf|nsz|contract> %acc{c}, %selected_old_scale : vector<8xf32>\n"
for c in range(8):
    K += f"    %next{c} = vector.mma %probability, %v{c}, %rescaled{c} : vector<16xf16>, vector<16xf16>, vector<8xf32>\n"
K += "    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)\n"
if PREFETCH:
    K += "    scf.yield %next_max_even, %next_sum_even, %next_max_odd, %next_sum_odd, " + ", ".join(f"%next{c}" for c in range(8)) + ", %k_next, %v_next : " + ", ".join(["vector<8xf32>"] * 12) + ", vector<16xf16>, vector<16xf16>\n  }\n"
else:
    K += "    scf.yield %next_max_even, %next_sum_even, %next_max_odd, %next_sum_odd, " + ", ".join(f"%next{c}" for c in range(8)) + " : " + ", ".join(["vector<8xf32>"] * 12) + "\n  }\n"
K += """  %selected_sum = scf.if %lane_group_even -> (vector<8xf32>) {
    scf.yield %final_sum_even : vector<8xf32>
  } else {
    scf.yield %final_sum_odd : vector<8xf32>
  }
"""
for c in range(8):
    K += f"  %out{c} = vector.divf<nnan|ninf|nsz|arcp> %final{c}, %selected_sum : vector<8xf32>\n"
K += """  // Publish one 16x16 fragment at a time through this wave's 1 KB stage: each lane
  // takes two vector4 slices, rows past the sequence dropped.
  %publish_row0 = index.div %lane, %c4 : index
  %publish_col_group = index.rem %lane, %c4 : index
  %publish_col = index.mul %publish_col_group, %c4 : index
  %publish_limit = index.sub %out_stride0, %c4 : index
  scf.for %fragment = [%c0 to %c8 step %c1] {
"""
sel = "%out0"
for j in range(1, 8):
    K += f"    %is{j} = index.cmp eq, %fragment, %c{j} : index\n    %pick{j} = scf.select %is{j}, %out{j}, {sel} : vector<8xf32>\n"
    sel = f"%pick{j}"
K += f"""    vector.fragment.store<result> {sel}, %result_view[%c0, %c0] shape [%m, %n] : vector<8xf32>, view<16x16xf32>
    kernel.barrier<workgroup> scope(subgroup) ordering(acq_rel)
    %frag_col = index.mul %fragment, %c16 : index
    %out_col_local = index.add %frag_col, %publish_col : index
    %out_column0 = index.add %head_base0, %out_col_local : index
    %out_column = index.assume %out_column0 [le(%out_column0, %publish_limit)] : index
    scf.for %half = [%c0 to %c2 step %c1] {{
      %row_offset = index.mul %half, %c8 : index
      %publish_row = index.add %publish_row0, %row_offset : index
      %local_row = index.add %query_origin0, %publish_row : index
      %present = index.cmp ult, %local_row, %tokens0 : index
      %in_range = index.cmp ult, %local_row, %token_count : index
      %writes = scalar.andi %present, %in_range : i1
      scf.if %writes {{
        %global_row = index.assume %local_row [lt(%local_row, %token_count)] : index
        %values = vector.load %result_view[%publish_row, %publish_col] : view<16x16xf32> -> vector<4xf32>
        %halves = vector.fptrunc %values : vector<4xf32> to vector<4xf16>
        vector.store %halves, %out_view[%global_row, %out_column] : vector<4xf16>, view<[%token_count]x[%out_stride0]xf16>
      }}
    }}
    kernel.barrier<workgroup> scope(subgroup) ordering(acq_rel)
  }}
  kernel.return
}}
"""
OUT.write_text(K)
print("wrote", OUT)
