"""host/block_sources.h: the block kernels (kernels/*.loom) as string literals, so the native
pipeline compiles them from the library itself and needs no bundle directory. Generated by the
build scripts; not committed."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "host/block_sources.h"


def main():
    text = ["#pragma once", "#include <map>", "#include <string>", "namespace krea_native {",
            "inline const std::map<std::string, std::string> &block_sources() {",
            "  static const std::map<std::string, std::string> sources = {"]
    for path in sorted((ROOT / "kernels").glob("*.loom")):
        source = path.read_text()
        assert ')loomsrc"' not in source, path
        text.append(f'      {{"{path.stem}", R"loomsrc({source})loomsrc"}},')
    text += ["  };", "  return sources;", "}", "} // namespace krea_native", ""]
    new = "\n".join(text)
    if not OUT.exists() or OUT.read_text() != new:
        OUT.write_text(new)


if __name__ == "__main__":
    main()
