"""kernels/attention_gqa64_f16_wmma.loom: the GQA attention with 64 keys per iteration.

Takes the generated 16-key kernel (tools/gen_attention.py) and replaces its key loop:
four 16-key score fragments share the eight query fragments, the running max and sum
are reduced across lanes once per 64 keys instead of once per 16, and the P*V phase
does its LDS reinterpretation for the four fragments behind one pair of barriers."""
import re
import sys
from pathlib import Path

SUB = int(sys.argv[1]) if len(sys.argv) > 1 else 4
KEYS = 16 * SUB

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "kernels/attention_gqa_f16_wmma.loom"
OUT = ROOT / f"kernels/attention_gqa{KEYS}_f16_wmma.loom"

s = SRC.read_text()
s = s.replace("krea2_attention_gqa_f16_wmma", f"krea2_attention_gqa{KEYS}_f16_wmma").replace("krea2.attention_gqa_f16_wmma", f"krea2.attention_gqa{KEYS}_f16_wmma").replace("krea2_attention_gqa_gfx11", f"krea2_attention_gqa{KEYS}_gfx11")
s = s.replace("// GENERATED by tools/gen_attention.py; edit the generator.",
              f"// {KEYS} keys per iteration: {SUB} score fragments per query tile share the eight query\n// fragments, one cross-lane max and one sum per 64 keys, one barrier pair per 64 keys.\n//\n// GENERATED by tools/gen_attention64.py from the 16-key kernel; edit the generator.")
# scratch: four 16x16 f16 tiles
s = s.replace("  %scratch_bytes = index.constant 512 : offset\n", f"  %scratch_bytes = index.constant {512 * SUB} : offset\n")
s = s.replace("  %scratch_view = buffer.view %scratch[%c0_offset] : buffer -> view<16x16xf16>\n",
              f"  %scratch_view = buffer.view %scratch[%c0_offset] : buffer -> view<{KEYS}x16xf16>\n")
# key blocks of 64
s = s.replace("  %key_tile_count = index.add %tiles_per_image, %c0 : index\n",
              f"  %ckm1 = index.constant {KEYS - 1} : index\n  %ckeys = index.constant {KEYS} : index\n  %tokens_km1 = index.add %tokens_per_image0, %ckm1 : index\n  %key_block_count = index.div %tokens_km1, %ckeys : index\n")
start = s.index("  %final_max_even, %final_sum_even")
end = s.index("  %selected_sum = scf.if %lane_group_even")
hdr_end = s.index("{\n", start) + 2
header = s[start:hdr_end].replace("scf.for %key_tile = [%c0 to %key_tile_count step %c1]", "scf.for %key_block = [%c0 to %key_block_count step %c1]")

def sub_tile_setup(j):
    o = f"    %ko{j}_0 = index.add %key_block_origin, %c{16*j} : index\n" if j else "    %ko0_0 = index.add %key_block_origin, %c0 : index\n"
    o += f"    %ko{j} = index.assume %ko{j}_0 [le(%ko{j}_0, %tile_origin_limit), mul(%ko{j}_0, 16)] : index\n"
    o += f"    %key_row{j}_0 = index.add %ko{j}, %lane_column : index\n"
    o += f"    %key_row{j} = index.assume %key_row{j}_0 [lt(%key_row{j}_0, %padded_tokens)] : index\n"
    o += f"    %key_valid{j} = index.cmp ult, %key_row{j}_0, %tokens_per_image0 : index\n"
    return o

def scores_all():
    """Channel-outer: each query fragment is loaded once and multiplied into the four
    sub-tiles' score accumulators, so only four score fragments and one query fragment
    are live (holding all eight query fragments spilled)."""
    o = ""
    prev = {j: "%init" for j in range(SUB)}
    for c in range(8):
        ch = "%kv_base0" if c == 0 else f"%kv_channel{c}"
        o += (f"    %q_channel{c} = index.add %head_base0, %c{16*c} : index\n" if c else "    %q_channel0 = index.add %head_base0, %c0 : index\n")
        o += f"    %lhs{c} = vector.fragment.load<lhs> %q_view[%query_origin0, %q_channel{c}] shape [%m, %k_frag] : view<[%padded_tokens]x[%q_stride0]xf16> -> vector<16xf16>\n"
        if c:
            o += f"    %kv_channel{c} = index.add %kv_base0, %c{16*c} : index\n"
        for j in range(SUB):
            o += f"    %k_data{j}_{c} = vector.load %k_view[%key_row{j}, {ch}] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>\n"
            o += f"    %rhs{j}_{c} = vector.fragment<rhs> %k_data{j}_{c} shape [%k_frag, %n] : vector<16xf16>\n"
            out = f"%raw{j}" if c == 7 else f"%qk{j}_{c}"
            o += f"    {out} = vector.mma %lhs{c}, %rhs{j}_{c}, {prev[j]} : vector<16xf16>, vector<16xf16>, vector<8xf32>\n"
            prev[j] = out
    for j in range(SUB):
        o += f"    %scaled{j}_0 = vector.mulf<reassoc|nnan|ninf|nsz|contract> %raw{j}, %scale_vector : vector<8xf32>\n"
        o += f"    %scaled{j} = scf.if %key_valid{j} -> (vector<8xf32>) {{\n      scf.yield %scaled{j}_0 : vector<8xf32>\n    }} else {{\n      scf.yield %negative_vector : vector<8xf32>\n    }}\n"
    return o

body = "    %key_block_origin = index.mul %key_block, %ckeys : index\n"
for j in range(SUB):
    body += sub_tile_setup(j)
body += scores_all()
# block max over the four fragments, then across lanes per row group
body += ("    %bm01 = vector.maxnumf %scaled0, %scaled1 : vector<8xf32>\n" + ("    %bm23 = vector.maxnumf %scaled2, %scaled3 : vector<8xf32>\n    %block_scores = vector.maxnumf %bm01, %bm23 : vector<8xf32>\n" if SUB == 4 else "    %block_scores = index.add %c0, %c0 : index\n".replace("%block_scores = index.add %c0, %c0 : index", "%block_scores = vector.maxnumf %bm01, %bm01 : vector<8xf32>")))
body += """    %even_scores = scf.if %lane_group_even -> (vector<8xf32>) {
      scf.yield %block_scores : vector<8xf32>
    } else {
      scf.yield %negative_vector : vector<8xf32>
    }
    %odd_scores = scf.if %lane_group_even -> (vector<8xf32>) {
      scf.yield %negative_vector : vector<8xf32>
    } else {
      scf.yield %block_scores : vector<8xf32>
    }
    %tile_max_even = kernel.workgroup.reduce<maxnumf> %even_scores : vector<8xf32>
    %tile_max_odd = kernel.workgroup.reduce<maxnumf> %odd_scores : vector<8xf32>
    %next_max_even = vector.maxnumf %max_even, %tile_max_even : vector<8xf32>
    %next_max_odd = vector.maxnumf %max_odd, %tile_max_odd : vector<8xf32>
    %selected_max = scf.if %lane_group_even -> (vector<8xf32>) {
      scf.yield %next_max_even : vector<8xf32>
    } else {
      scf.yield %next_max_odd : vector<8xf32>
    }
"""
for j in range(SUB):
    body += f"""    %delta{j} = vector.subf<reassoc|nnan|ninf|nsz> %scaled{j}, %selected_max : vector<8xf32>
    %raw_weight{j} = vector.expf<afn> %delta{j} : vector<8xf32>
    %weight{j} = scf.if %key_valid{j} -> (vector<8xf32>) {{
      scf.yield %raw_weight{j} : vector<8xf32>
    }} else {{
      scf.yield %zero_vector : vector<8xf32>
    }}
"""
body += ("    %w01 = vector.addf<reassoc|nnan|ninf|nsz> %weight0, %weight1 : vector<8xf32>\n" + ("    %w23 = vector.addf<reassoc|nnan|ninf|nsz> %weight2, %weight3 : vector<8xf32>\n    %weight_sum = vector.addf<reassoc|nnan|ninf|nsz> %w01, %w23 : vector<8xf32>\n" if SUB == 4 else "    %weight_sum = vector.addf<reassoc|nnan|ninf|nsz> %w01, %zero_vector : vector<8xf32>\n"))
body += """    %even_weight = scf.if %lane_group_even -> (vector<8xf32>) {
      scf.yield %weight_sum : vector<8xf32>
    } else {
      scf.yield %zero_vector : vector<8xf32>
    }
    %odd_weight = scf.if %lane_group_even -> (vector<8xf32>) {
      scf.yield %zero_vector : vector<8xf32>
    } else {
      scf.yield %weight_sum : vector<8xf32>
    }
    %tile_sum_even = kernel.workgroup.reduce<addf> %even_weight : vector<8xf32>
    %tile_sum_odd = kernel.workgroup.reduce<addf> %odd_weight : vector<8xf32>
    %old_delta_even = vector.subf<reassoc|nnan|ninf|nsz> %max_even, %next_max_even : vector<8xf32>
    %old_delta_odd = vector.subf<reassoc|nnan|ninf|nsz> %max_odd, %next_max_odd : vector<8xf32>
    %old_scale_even = vector.expf<afn> %old_delta_even : vector<8xf32>
    %old_scale_odd = vector.expf<afn> %old_delta_odd : vector<8xf32>
    %scaled_sum_even = vector.mulf<reassoc|nnan|ninf|nsz|contract> %sum_even, %old_scale_even : vector<8xf32>
    %scaled_sum_odd = vector.mulf<reassoc|nnan|ninf|nsz|contract> %sum_odd, %old_scale_odd : vector<8xf32>
    %next_sum_even = vector.addf<reassoc|nnan|ninf|nsz> %scaled_sum_even, %tile_sum_even : vector<8xf32>
    %next_sum_odd = vector.addf<reassoc|nnan|ninf|nsz> %scaled_sum_odd, %tile_sum_odd : vector<8xf32>
    %selected_old_scale = scf.if %lane_group_even -> (vector<8xf32>) {
      scf.yield %old_scale_even : vector<8xf32>
    } else {
      scf.yield %old_scale_odd : vector<8xf32>
    }
"""
for j in range(SUB):
    body += f"    vector.fragment.store<result> %weight{j}, %scratch_view[%c{16*j}, %c0] shape [%m, %n] : vector<8xf32>, view<{KEYS}x16xf16>\n" if j else \
            f"    vector.fragment.store<result> %weight0, %scratch_view[%c0, %c0] shape [%m, %n] : vector<8xf32>, view<{KEYS}x16xf16>\n"
body += "    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)\n"
for j in range(SUB):
    body += f"    %probability{j} = vector.fragment.load<lhs> %scratch_view[%c{16*j}, %c0] shape [%m, %k_frag] : view<{KEYS}x16xf16> -> vector<16xf16>\n" if j else \
            f"    %probability0 = vector.fragment.load<lhs> %scratch_view[%c0, %c0] shape [%m, %k_frag] : view<{KEYS}x16xf16> -> vector<16xf16>\n"
for c in range(8):
    ch = "%kv_base0" if c == 0 else f"%kv_channel{c}"
    body += f"    %vt_row{c} = index.add {ch}, %lane_column : index\n"
    body += f"    %rescaled{c} = vector.mulf<reassoc|nnan|ninf|nsz|contract> %acc{c}, %selected_old_scale : vector<8xf32>\n"
for c in range(8):
    prev = f"%rescaled{c}"
    for j in range(SUB):
        body += f"    %v_data{j}_{c} = vector.load %vt_view[%vt_row{c}, %ko{j}] : view<[%kv_stride0]x[%padded_tokens]xf16> -> vector<16xf16>\n"
        body += f"    %v{j}_{c} = vector.fragment<rhs> %v_data{j}_{c} shape [%k_frag, %n] : vector<16xf16>\n"
        out = f"%next{c}" if j == SUB - 1 else f"%pv{j}_{c}"
        body += f"    {out} = vector.mma %probability{j}, %v{j}_{c}, {prev} : vector<16xf16>, vector<16xf16>, vector<8xf32>\n"
        prev = out
body += "    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)\n"
body += "    scf.yield %next_max_even, %next_sum_even, %next_max_odd, %next_sum_odd, " + ", ".join(f"%next{c}" for c in range(8)) + " : " + ", ".join(["vector<8xf32>"] * 12) + "\n  }\n"
s = s[:start] + header + body + s[end:]
# the old loop defined %key_origin0/%key_row used nowhere else now; the old per-tile constants stay
OUT.write_text(s)
print("wrote", OUT)
