"""Build complete Unicode category/NFC tables; no Python dependency at inference."""

from pathlib import Path
import unicodedata as u

ROOT = Path(__file__).resolve().parent.parent


def ranges(predicate):
    out = []
    for cp in range(0x110000):
        if predicate(chr(cp)):
            if out and out[-1][1] + 1 == cp:
                out[-1][1] = cp
            else:
                out.append([cp, cp])
    return out


def main():
    if u.unidata_version != "16.0.0":
        raise RuntimeError("Regeneration requires Python Unicode 16.0.0 tables")
    lines = [
        "// Generated by tools/gen_unicode.py from Unicode " + u.unidata_version + ".",
        "#pragma once",
        "#include <cstdint>",
        "namespace krea_native::unicode_data {",
        "struct Range { uint32_t first,last; };",
    ]
    for name, cat in [("letters", "L"), ("numbers", "N")]:
        lines.append("inline constexpr Range " + name + "[] = {")
        lines.extend(
            "{%d,%d}," % tuple(r)
            for r in ranges(lambda c: u.category(c).startswith(cat))
        )
        lines.append("};")
    lines += [
        "struct Combining { uint32_t code; unsigned value; };",
        "inline constexpr Combining combining[] = {",
    ]
    for cp in range(0x110000):
        c = u.combining(chr(cp))
        if c:
            lines.append("{%d,%d}," % (cp, c))
    lines += [
        "};",
        "struct Decomposition { uint32_t code,a,b; };",
        "inline constexpr Decomposition decompositions[] = {",
    ]
    composition = []
    for cp in range(0x110000):
        raw = u.decomposition(chr(cp))
        if not raw or raw.startswith("<") or 0xAC00 <= cp < 0xAC00 + 11172:
            continue
        ds = [int(x, 16) for x in raw.split()]
        assert len(ds) <= 2
        lines.append("{%d,%d,%d}," % (cp, ds[0], ds[1] if len(ds) > 1 else 0))
        if len(ds) == 2 and u.normalize("NFC", "".join(map(chr, ds))) == chr(cp):
            composition.append(((ds[0] << 21) | ds[1], cp))
    lines += [
        "};",
        "struct Composition { uint64_t pair; uint32_t code; };",
        "inline constexpr Composition compositions[] = {",
    ]
    lines += ["{%dULL,%d}," % p for p in sorted(composition)]
    lines += ["};", "}\n"]
    (ROOT / "host/unicode_data.h").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
