"""Generate gfx11 smoothed INT4-QK / fp16-PV GQA attention.

Shares the tested online-softmax/PV/epilogue generator. Preprocessing supplies
per-token scales and the float32 Q-mean times centered-K score correction.
"""
import os
from pathlib import Path
import re
import runpy

ROOT = Path(__file__).resolve().parent.parent


def generate():
    stem = "attention_sage_i4"
    env = dict(os.environ)
    try:
        os.environ.update(ATTN_STEM=stem, ATTN_TILE="16", ATTN_HOIST="8", ATTN_QLDS="0", ATTN_NO_WRITE="1")
        s = runpy.run_path(str(ROOT / "tools/gen_attention_lds.py"))["K"]
    finally:
        os.environ.clear()
        os.environ.update(env)
    s = s[s.index("amdgpu.target"):]
    s = "// GENERATED by tools/gen_sage_attention.py. Smoothed INT4 QK, fp16 PV.\n" + s
    s = s.replace("%v: buffer, %out: buffer)", "%v: buffer, %qs: buffer, %ks: buffer, %correction: buffer, %out: buffer)")
    s = s.replace("  %zero_acc =", "  %i4_schema = encoding.define #encoding.operand<element_format=i4, payload_elements=16, payload_registers=2> : encoding<schema>\n  %zero_i32 = vector.constant 0 : vector<8xi32>\n  %zero_acc =")
    s = s.replace("  %init =", "  %init_i4 = vector.fragment<init> %zero_i32 shape [%m, %n] : vector<8xi32>\n  %init =")
    s = s.replace("  %c136 = index.constant 136 : index", "  %c20 = index.constant 20 : index")
    s = s.replace("index.constant 4352 : offset", "index.constant 1280 : offset")
    s = s.replace("index.constant 10496 : offset", "index.constant 7424 : offset")
    s = s.replace("index.constant 12544 : offset", "index.constant 9472 : offset")
    s = s.replace("view<16x136xf16>", "view<16x20xi32>")
    insert = '''  %q_packed_stride = index.div %q_stride0, %c8 : index
  %k_packed_stride = index.div %kv_stride0, %c8 : index
  %query_lane0 = index.add %query_origin0, %lane_column : index
  %query_lane = index.assume %query_lane0 [lt(%query_lane0, %padded_tokens)] : index
  %qs_global = buffer.assume.memory_space<global> %qs : buffer
  %ks_global = buffer.assume.memory_space<global> %ks : buffer
  %corr_global = buffer.assume.memory_space<global> %correction : buffer
  %qs_view = buffer.view %qs_global[%c0_offset] : buffer -> view<[%padded_tokens]x[%head_limit]xf32>
  %ks_view = buffer.view %ks_global[%c0_offset] : buffer -> view<[%padded_tokens]x[%kv_head_limit]xf32>
  %mean_c63 = index.constant 63 : index
  %mean_rounded = index.add %tokens0, %mean_c63 : index
  %mean_tiles = index.div %mean_rounded, %c64 : index
  %mean_tile_id = index.div %query_origin0, %c64 : index
  %corr_rows = index.mul %head_limit, %mean_tiles : index
  %corr_row0 = index.mul %head, %mean_tiles : index
  %corr_row1 = index.add %corr_row0, %mean_tile_id : index
  %corr_row = index.assume %corr_row1 [lt(%corr_row1, %corr_rows)] : index
  %corr_view = buffer.view %corr_global[%c0_offset] : buffer -> view<[%corr_rows]x[%padded_tokens]xf32>
'''
    s = s.replace("  %q_view =", insert + "  %q_view =")
    s = s.replace("view<[%padded_tokens]x[%q_stride0]xf16>", "view<[%padded_tokens]x[%q_packed_stride]xi32>")
    s = s.replace("view<[%padded_tokens]x[%kv_stride0]xf16>", "view<[%padded_tokens]x[%k_packed_stride]xi32>", 1)
    # Replace resident Q fragments and construct the row-scale vector matching
    # the gfx11 accumulator map: row=2*element+lane/16, column=lane%16.
    start = s.index("  %q_channel0 =")
    end = s.index("  %final_max", start)
    q = "  %packed_head = index.div %head_base0, %c8 : index\n"
    for c in range(8):
        q += f'''  %qc{c} = index.constant {c*2} : index
  %qcol0_{c} = index.add %packed_head, %qc{c} : index
  %qlimit{c} = index.sub %q_packed_stride, %c2 : index
  %qcol{c} = index.assume %qcol0_{c} [le(%qcol0_{c}, %qlimit{c}), mul(%qcol0_{c}, 2)] : index
  %qdata{c} = vector.load %q_view[%query_lane, %qcol{c}] : view<[%padded_tokens]x[%q_packed_stride]xi32> -> vector<2xi32>
  %lhs{c} = vector.fragment<lhs> %qdata{c} shape [%m, %k_frag] using {{schema = %i4_schema : encoding<schema>}} : vector<2xi32>
  %qr0_{c} = index.add %query_origin0, %qc{c} : index
  %qr1_{c} = index.add %qr0_{c}, %lane_group : index
  %qr{c} = index.assume %qr1_{c} [lt(%qr1_{c}, %padded_tokens)] : index
  %qs{c} = view.load %qs_view[%qr{c}, %head] : view<[%padded_tokens]x[%head_limit]xf32> -> f32
  %qsv{c} = vector.insert %qs{c} into {"%zero_vector" if c == 0 else f"%qsv{c-1}"}[{c}] : f32, vector<8xf32>
'''
    s = s[:start] + q + s[end:]
    s = s.replace("    %k_chunk = vector.load %k_view[%st_row, %st_col] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>", '''    %pkcol0 = index.div %st_col, %c8 : index
    %pklimit = index.sub %k_packed_stride, %c2 : index
    %pkcol = index.assume %pkcol0 [le(%pkcol0, %pklimit), mul(%pkcol0, 2)] : index
    %pkchunk = index.div %st_chunk, %c8 : index
    %k_chunk = vector.load %k_view[%st_row, %pkcol] : view<[%padded_tokens]x[%k_packed_stride]xi32> -> vector<2xi32>''')
    s = s.replace("vector.store %k_chunk, %k_tile[%st_key, %st_chunk] : vector<16xf16>", "vector.store %k_chunk, %k_tile[%st_key, %pkchunk] : vector<2xi32>")
    start = s.index("    %k_data0 =")
    end = s.index("    %scaled0 =", start)
    dot = ""
    for c in range(8):
        dot += f'''    %k_data{c} = vector.load %k_tile[%lane_column, %qc{c}] : view<16x20xi32> -> vector<2xi32>
    %rhs{c} = vector.fragment<rhs> %k_data{c} shape [%k_frag, %n] using {{schema = %i4_schema : encoding<schema>}} : vector<2xi32>
    %dot{c} = vector.mma %lhs{c}, %rhs{c}, {"%init_i4" if c == 0 else f"%dot{c-1}"} : vector<2xi32>, vector<2xi32>, vector<8xi32>
'''
    dot += '''    %key_bounded = index.assume %local_key [lt(%local_key, %padded_tokens)] : index
    %kscalar = view.load %ks_view[%key_bounded, %kv_head] : view<[%padded_tokens]x[%kv_head_limit]xf32> -> f32
    %ksv = vector.splat %kscalar : vector<8xf32>
    %scales = vector.mulf %qsv7, %ksv : vector<8xf32>
    %dotf = vector.sitofp %dot7 : vector<8xi32> to vector<8xf32>
    %dequantized = vector.mulf %dotf, %scales : vector<8xf32>
    %bias = view.load %corr_view[%corr_row, %key_bounded] : view<[%corr_rows]x[%padded_tokens]xf32> -> f32
    %biasv = vector.splat %bias : vector<8xf32>
    %raw_scores = vector.addf %dequantized, %biasv : vector<8xf32>
'''
    s = s[:start] + dot + s[end:]
    return s


def pingpong(s):
    """Load the following tile while consuming the current LDS slot.

    The extra key/value tile is always inside the zeroed capacity headroom.
    Workgroup barriers protect slot reuse; no Hopper-only TMA operation is used.
    """
    s = s.replace("attention_sage_i4", "attention_sage_i4_pingpong")
    s = s.replace("index.constant 7424 : offset", "index.constant 14848 : offset")
    s = s.replace("index.constant 9472 : offset", "index.constant 16896 : offset")
    s = s.replace("  %k_tile =", "  %k_initial =").replace("  %v_tile =", "  %v_initial =")
    loop = s.index("  %final_max")
    begin = s.index("    %key_origin1", loop)
    end = s.index("    %local_key", begin)
    stage = s[begin:end]
    names = re.findall(r"^    (%[A-Za-z_][A-Za-z_0-9]*) =", stage, re.M)
    def rename(text, suffix):
        mapping = {name: name + suffix for name in names}
        return re.sub(r"%[A-Za-z_][A-Za-z_0-9]*", lambda m: mapping.get(m[0], m[0]), text)
    initial = rename(stage.replace("%key_tile,", "%c0,"), "_initial")
    initial = initial.replace("%k_tile[", "%k_initial[").replace("%v_tile[", "%v_initial[")
    store = stage.index("    vector.store %k_chunk")
    fetch = rename(stage[:store], "_next").replace("%key_tile,", "%next_key_tile,")
    store_next = rename(stage[store:], "_next")
    store_next = store_next.replace("%k_tile[", "%k_other[").replace("%v_tile[", "%v_other[")
    store_next = store_next.replace("    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)\n", "")
    indices = stage[:stage.index("    // stage K")]
    views = """    %slot0 = index.rem %key_tile, %c2 : index
    %slot = index.assume %slot0 [range(%slot0, 0, 1)] : index
    %other_next = index.add %key_tile, %c1 : index
    %other0 = index.rem %other_next, %c2 : index
    %other = index.assume %other0 [range(%other0, 0, 1)] : index
    %slot_bytes = index.constant 7424 : offset
    %current_offset = index.scale %slot, %slot_bytes : index, offset -> offset
    %other_offset = index.scale %other, %slot_bytes : index, offset -> offset
    %current_v = index.add %current_offset, %v_tile_offset : offset
    %other_v = index.add %other_offset, %v_tile_offset : offset
    %k_tile = buffer.view %lds[%current_offset] : buffer -> view<16x20xi32>
    %v_tile = buffer.view %lds[%current_v] : buffer -> view<128x24xf16>
    %k_other = buffer.view %lds[%other_offset] : buffer -> view<16x20xi32>
    %v_other = buffer.view %lds[%other_v] : buffer -> view<128x24xf16>
    %next_key_tile = index.add %key_tile, %c1 : index
"""
    s = s[:begin] + indices + views + fetch + s[end:]
    ending = s.index("    kernel.barrier<workgroup> scope(workgroup)", begin)
    s = s[:ending] + store_next + s[ending:]
    s = s[:loop] + initial + s[loop:]
    return s


def transposed_v(s):
    """H3's V layout: transpose once globally, use wide LDS stores per key tile."""
    s = s.replace('view<[%padded_tokens]x[%kv_stride0]xf16>', 'view<[%kv_stride0]x[%padded_tokens]xf16>')
    s = s.replace('  %init =', '''  %vchan0 = index.add %kv_base0, %workitem : index
  %vchan = index.assume %vchan0 [lt(%vchan0, %kv_stride0)] : index
  %init =''')
    s = s.replace('%v_view[%st_row_v, %st_col_v]', '%v_view[%vchan, %key_origin0]')
    s, n = re.subn(r'    %ve\d+ = vector.extract %v_chunk\[\d+\] : vector<16xf16> -> f16\n    %vr\d+ = index.add %st_chunk_v, %cj\d+ : index\n    view.store %ve\d+, %v_tile\[%vr\d+, %st_key_v\] : f16, view<128x24xf16>\n', '',s)
    assert n == 16, n
    s = s.replace('    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)\n', '    vector.store %v_chunk, %v_tile[%workitem, %c0] : vector<16xf16>, view<128x24xf16>\n    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)\n',1)
    return s

def double_buffer(s):
    """Alternate slots to remove the trailing barrier without carrying prefetch.

    The leading barrier of tile i+1 ensures every wave finished reading tile i
    before any wave can reuse its slot in tile i+2. The final barrier protects
    the epilogue, whose result staging aliases K/V storage.
    """
    s = s.replace('index.constant 7424 : offset', 'index.constant 14848 : offset').replace('index.constant 9472 : offset', 'index.constant 16896 : offset')
    s = s.replace('  %k_tile =', '  %k_unused =').replace('  %v_tile =', '  %v_unused =')
    i = s.index('    // stage K')
    s = s[:i]+'''    %slot = index.rem %key_tile, %c2 : index
    %slot_bytes = index.constant 7424 : offset
    %slot_offset = index.scale %slot, %slot_bytes : index, offset -> offset
    %v_offset = index.add %slot_offset, %v_tile_offset : offset
    %k_tile = buffer.view %lds[%slot_offset] : buffer -> view<16x20xi32>
    %v_tile = buffer.view %lds[%v_offset] : buffer -> view<128x24xf16>
'''+s[i:]
    s = s.replace('    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)\n    scf.yield %next_max', '    scf.yield %next_max')
    s = s.replace('  // the row sum:', '  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)\n  // the row sum:')
    return s

def waves8(s):
    """Share one K/V tile across two 16-query tiles and four GQA heads each."""
    # two consecutive query tiles, each with four grouped-query heads
    s = s.replace('  kernel.launch.config', '  %c2 = index.constant 2 : index\n  %c256 = index.constant 256 : index\n  %tiles1 = index.add %tiles, %c1 : index\n  %groups = index.div %tiles1, %c2 : index\n  kernel.launch.config',1)
    s = s.replace('workgroups(%tiles,', 'workgroups(%groups,').replace('workgroup_size(%c128,', 'workgroup_size(%c256,')
    s = s.replace('range(%wave0, 0, 3)', 'range(%wave0, 0, 7)')
    s = s.replace('  %head1 = index.add %head0, %wave : index','  %head_wave = index.rem %wave, %c4 : index\n  %head1 = index.add %head0, %head_wave : index')
    s = s.replace('  %tile_in_image = index.rem %tile_id, %tiles_per_image : index', '''  %tile_base = index.mul %tile_id, %c2 : index
  %tile_wave = index.div %wave, %c4 : index
  %tile_index = index.add %tile_base, %tile_wave : index
  %tile_last = index.sub %tiles_per_image, %c1 : index
  %tile_in_image = index.min %tile_index, %tile_last : index
  %tile_present = index.cmp ult, %tile_index, %tiles_per_image : index''')
    # Split K and V staging between the two wave groups. Both consume the tile.
    s = s.replace('  %workitem = kernel.workitem.id<x> : index', '''  %workitem_raw = kernel.workitem.id<x> : index
  %workitem = index.rem %workitem_raw, %c128 : index
  %stage_active = index.cmp ult, %workitem_raw, %c128 : index''')
    i = s.index('    // stage K'); j = s.index('    kernel.barrier<workgroup> scope(workgroup)',i)
    stage = s[i:j]
    lines = stage.splitlines(True)
    klines = ''.join(l for l in lines if '%v_chunk' not in l and '%st_row_v' not in l)
    vlines = ''.join(l for l in lines if '%v_chunk' in l)
    s = s[:i]+'    scf.if %stage_active {\n'+klines+'    } else {\n'+vlines+'    }\n'+s[j:]
    # Eight waves need eight 512-byte scratch slots after the two 7424-byte
    # K/V slots that double_buffer laid out; this step must follow it.
    before = s
    s = s.replace('index.constant 16896 : offset', 'index.constant 18944 : offset')
    assert s != before, 'waves8 expects the double_buffer LDS layout'
    s = s.replace('      %writes = scalar.andi %present, %in_range : i1', '      %valid_row = scalar.andi %present, %in_range : i1\n      %writes = scalar.andi %valid_row, %tile_present : i1')
    return s


if __name__ == "__main__":
    source = generate()
    for name, text in (("attention_sage_i4_fast", waves8(double_buffer(transposed_v(source))).replace("attention_sage_i4", "attention_sage_i4_fast")),
                       ("attention_sage_i4_fast_prefetch", pingpong(transposed_v(source)).replace("attention_sage_i4_pingpong", "attention_sage_i4_fast_prefetch"))):
        out = ROOT / "kernels" / (name + ".loom")
        out.write_text(text)
        print(out)
