"""kernels/attention_gqa_lds_f16_wmma.loom: GQA attention with K/V tiles staged in LDS.

One workgroup of four waves per (16 query rows, key-value head): wave w is query head
kv_head*4 + w. Per 16-key tile the workgroup loads the K tile [16][128] and the V tile
[16][128] cooperatively and coalesced (each lane 32 contiguous bytes), stores them in
LDS, and all four waves take their operands from there: K's rhs by hand (lane = key,
16 contiguous channels), V's rhs as dense fragment loads from the tile rows. The online softmax,
running statistics and epilogue are the tested 16-key kernel's."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
import os
TILE = int(os.environ.get("ATTN_TILE", "16"))          # keys per staged tile (16 or 32)
STEM = os.environ.get("ATTN_STEM", "attention_gqa_lds_f16_wmma")
assert TILE in (16, 32)
OUT = ROOT / ("kernels" if STEM == "attention_gqa_lds_f16_wmma" else "experiments") / f"{STEM}.loom"
NS, SYM = "krea2." + STEM, "krea2_" + STEM
ROW = 136   # LDS row length in halves for a 128-channel tile (272-byte rows)
import os
HOIST = int(os.environ.get("ATTN_HOIST", "4"))   # Q fragments hoisted out of the key loop
QLDS = os.environ.get("ATTN_QLDS", "1") == "1"    # the other Q fragments staged once per wave in LDS
QROW = (8 - HOIST) * 16 + 8 if QLDS and HOIST < 8 else 0   # halves per staged Q row
assert HOIST % 2 == 0, "the Q staging loop moves 32 chunks per iteration: HOIST must be even"
VROW = TILE + 8   # the V tile is staged transposed, [channel][key]: TILE keys + 8 pad halves per row
SCRATCH = 512 * (TILE // 16)   # per-wave f16 probability scratch: one 16x16 tile per 16 keys


K = f"""// GQA attention for Krea 2 with K/V tiles staged in LDS: one workgroup of four waves
// per (16 query rows, key-value head); wave w owns query head kv_head*4 + w. Each
// 16-key tile of K and V is loaded once, coalesced (a lane reads 32 contiguous bytes),
// into LDS and serves all four heads; K's rhs fragments are assembled from the LDS rows
// (lane = key, 16 contiguous channels), V's as dense rhs loads from the tile rows (the tile's [key][channel] layout is the rhs' logical [k][n]). Online
// softmax with running max and sum per lane group, eight accumulators for the 128
// output channels, f16 out. q [tokens][q_stride], k and v [tokens][kv_stride] (natural
// layout, no transpose needed), token_capacity >= tokens + 16 with zero headroom.
//
// GENERATED by tools/gen_attention_lds.py; edit the generator.
amdgpu.target<gfx11-generic> @{SYM}_gfx11 {{subgroup_size = 32}}

config.decl @{NS}.q_stride : %value: index where [range(%value, 128, 32768), mul(%value, 128)]

config.decl @{NS}.kv_stride : %value: index where [range(%value, 128, 32768), mul(%value, 128)]

config.decl @{NS}.out_stride : %value: index where [range(%value, 128, 32768), mul(%value, 128)]

config.decl @{NS}.tokens : %value: index where [range(%value, 16, 65536)]

config.decl @{NS}.token_capacity : %value: index where [range(%value, 32, 1048576), mul(%value, 16)]

config.decl @{NS}.scale : f32

kernel.def target(@{SYM}_gfx11) export("{SYM}") @{SYM}(%token_count: index, %kv_head_count: index) {{
  %c1 = index.constant 1 : index
  %c15 = index.constant 15 : index
  %c16 = index.constant 16 : index
  %c128 = index.constant 128 : index
  %tokens0 = config.get @{NS}.tokens : index
  %rounded = index.add %tokens0, %c15 : index
  %tiles = index.div %rounded, %c16 : index
  kernel.launch.config workgroups(%tiles, %kv_head_count, %c1) workgroup_size(%c128, %c1, %c1) : index
}} launch(%token_count: index, %q: buffer, %k: buffer, %v: buffer, %out: buffer) {{
  %q_stride0 = config.get @{NS}.q_stride : index
  %kv_stride0 = config.get @{NS}.kv_stride : index
  %out_stride0 = config.get @{NS}.out_stride : index
  %tokens0 = config.get @{NS}.tokens : index
  %padded_tokens = config.get @{NS}.token_capacity : index
  %scale = config.get @{NS}.scale : f32
  %c0 = index.constant 0 : index
  %c1 = index.constant 1 : index
  %c2 = index.constant 2 : index
  %c3 = index.constant 3 : index
  %c4 = index.constant 4 : index
  %c5 = index.constant 5 : index
  %c6 = index.constant 6 : index
  %c7 = index.constant 7 : index
  %c8 = index.constant 8 : index
  %c15 = index.constant 15 : index
  %c16 = index.constant 16 : index
  %c32 = index.constant 32 : index
  %c48 = index.constant 48 : index
  %c64 = index.constant 64 : index
  %c80 = index.constant 80 : index
  %c96 = index.constant 96 : index
  %c112 = index.constant 112 : index
  %c128 = index.constant 128 : index
  %c{ROW} = index.constant {ROW} : index
{"  %c31 = index.constant 31 : index" + chr(10) if TILE == 32 else ""}  %c0_offset = index.constant 0 : offset
  %k_tile_offset = index.constant 0 : offset
  %v_tile_offset = index.constant {TILE * ROW * 2} : offset
  %scratch_offset = index.constant {TILE * ROW * 2 + 128 * VROW * 2} : offset
  // the result stage aliases the K/V tiles: it is used only after the loop's final barrier
  %result_offset = index.constant 0 : offset
  %q_tile_offset = index.constant {TILE * ROW * 2 + 128 * VROW * 2 + 4 * SCRATCH} : offset
  %lds_bytes = index.constant {TILE * ROW * 2 + 128 * VROW * 2 + 4 * SCRATCH + 4 * 16 * QROW * 2} : offset
  %m = index.constant 16 : index
  %n = index.constant 16 : index
  %k_frag = index.constant 16 : index
  %zero_f32 = scalar.constant 0.0 : f32
  %negative_large = scalar.constant -1000000000.0 : f32
  %zero_acc = vector.constant 0.0 : vector<8xf32>
  %cj0 = index.constant 0 : index
  %cj1 = index.constant 1 : index
  %cj2 = index.constant 2 : index
  %cj3 = index.constant 3 : index
  %cj4 = index.constant 4 : index
  %cj5 = index.constant 5 : index
  %cj6 = index.constant 6 : index
  %cj7 = index.constant 7 : index
  %cj8 = index.constant 8 : index
  %cj9 = index.constant 9 : index
  %cj10 = index.constant 10 : index
  %cj11 = index.constant 11 : index
  %cj12 = index.constant 12 : index
  %cj13 = index.constant 13 : index
  %cj14 = index.constant 14 : index
  %cj15 = index.constant 15 : index
  %i32_1 = scalar.constant 1 : i32
  %i32_2 = scalar.constant 2 : i32
  %i32_4 = scalar.constant 4 : i32
  %i32_8 = scalar.constant 8 : i32
  %i32_32 = scalar.constant 32 : i32
  %zero_vector = vector.splat %zero_f32 : vector<8xf32>
  %negative_vector = vector.splat %negative_large : vector<8xf32>
  %scale_vector = vector.splat %scale : vector<8xf32>

  %tile_id = kernel.workgroup.id<x> : index
  %kv_head_raw = kernel.workgroup.id<y> : index
  %kv_head_limit = index.div %kv_stride0, %c128 : index
  %kv_head = index.rem %kv_head_raw, %kv_head_limit : index
  %workitem = kernel.workitem.id<x> : index
  %wave0 = kernel.subgroup.id : index
  %wave = index.assume %wave0 [range(%wave0, 0, 3)] : index
  %lane = kernel.subgroup.lane.id : index
  %lane_column = index.rem %lane, %c16 : index
  %lane_group = index.div %lane, %c16 : index
  %lane_group_even = index.cmp eq, %lane_group, %c0 : index
  // this wave's query head, and its channels in q and out
  %head_limit = index.div %out_stride0, %c128 : index
  %head0 = index.mul %kv_head, %c4 : index
  %head1 = index.add %head0, %wave : index
  %head = index.rem %head1, %head_limit : index
  %head_base0 = index.mul %head, %c128 : index
  %kv_base0 = index.mul %kv_head, %c128 : index
  %rounded = index.add %tokens0, %c15 : index
  %tiles_per_image = index.div %rounded, %c16 : index
  %tile_in_image = index.rem %tile_id, %tiles_per_image : index
  %query_origin0 = index.mul %tile_in_image, %c16 : index
  %tile_origin_limit = index.sub %padded_tokens, %c{TILE} : index

  %q_global = buffer.assume.memory_space<global> %q : buffer
  %k_global = buffer.assume.memory_space<global> %k : buffer
  %v_global = buffer.assume.memory_space<global> %v : buffer
  %out_global = buffer.assume.memory_space<global> %out : buffer
  %q_view = buffer.view %q_global[%c0_offset] : buffer -> view<[%padded_tokens]x[%q_stride0]xf16>
  %k_view = buffer.view %k_global[%c0_offset] : buffer -> view<[%padded_tokens]x[%kv_stride0]xf16>
  %v_view = buffer.view %v_global[%c0_offset] : buffer -> view<[%padded_tokens]x[%kv_stride0]xf16>
  %out_view = buffer.view %out_global[%c0_offset] : buffer -> view<[%token_count]x[%out_stride0]xf16>

  %lds = buffer.alloca<workgroup> align(16) %lds_bytes : buffer
  // K and V tiles: 16 keys x 128 channels, rows padded to {ROW} halves
  %k_tile = buffer.view %lds[%k_tile_offset] : buffer -> view<{TILE}x{ROW}xf16>
  %v_tile = buffer.view %lds[%v_tile_offset] : buffer -> view<128x{VROW}xf16>
  %wave_scratch_bytes = index.constant {SCRATCH} : offset
  %wave_scratch_offset0 = index.scale %wave, %wave_scratch_bytes : index, offset -> offset
  %wave_scratch_offset = index.add %scratch_offset, %wave_scratch_offset0 : offset
  %scratch_view = buffer.view %lds[%wave_scratch_offset] : buffer -> view<16x16xf16>
{"  %scratch_hi_offset = index.constant 512 : offset" + chr(10) + "  %wave_scratch_offset_hi = index.add %wave_scratch_offset, %scratch_hi_offset : offset" + chr(10) + "  %scratch_view_hi = buffer.view %lds[%wave_scratch_offset_hi] : buffer -> view<16x16xf16>" + chr(10) if TILE == 32 else ""}  %wave_result_bytes = index.constant 1024 : offset
  %wave_result_offset0 = index.scale %wave, %wave_result_bytes : index, offset -> offset
  %wave_result_offset = index.add %result_offset, %wave_result_offset0 : offset
  %result_view = buffer.view %lds[%wave_result_offset] : buffer -> view<16x16xf32>

  // cooperative staging map: lane -> key workitem/8, 16-channel chunk (workitem%8)*16
  %st_key = index.div %workitem, %c8 : index
  %st_chunk0 = index.rem %workitem, %c8 : index
  %st_chunk = index.mul %st_chunk0, %c16 : index
  %st_col0 = index.add %kv_base0, %st_chunk : index
  %kv_col_limit = index.sub %kv_stride0, %c16 : index
  %q_col_limit = index.sub %q_stride0, %c16 : index
  %st_col = index.assume %st_col0 [le(%st_col0, %kv_col_limit), mul(%st_col0, 16)] : index
  // V staging: lane -> (key = workitem mod 16, channel chunk = workitem / 16), transposed into LDS
  %st_key_v = index.rem %workitem, %c16 : index
  %st_chunk_v0 = index.div %workitem, %c16 : index
  %st_chunk_v = index.mul %st_chunk_v0, %c16 : index
  %st_col_v0 = index.add %kv_base0, %st_chunk_v : index
  %st_col_v = index.assume %st_col_v0 [le(%st_col_v0, %kv_col_limit), mul(%st_col_v0, 16)] : index
  %init = vector.fragment<init> %zero_acc shape [%m, %n] : vector<8xf32>
{"  %key_tile_count = index.add %tiles_per_image, %c0 : index" if TILE == 16 else "  %key_rounded = index.add %tokens0, %c31 : index" + chr(10) + "  %key_tile_count = index.div %key_rounded, %c32 : index"}
{"  %st_key_hi = index.add %st_key, %c16 : index" + chr(10) + "  %st_key_v_hi = index.add %st_key_v, %c16 : index" + chr(10) + "  %lane_column_hi = index.add %lane_column, %c16 : index" + chr(10) if TILE == 32 else ""}
"""
if QROW:
    K += f"""  %wave_q_bytes = index.constant {16 * QROW * 2} : offset
  %wave_q_offset0 = index.scale %wave, %wave_q_bytes : index, offset -> offset
  %wave_q_offset = index.add %q_tile_offset, %wave_q_offset0 : offset
  %q_tile = buffer.view %lds[%wave_q_offset] : buffer -> view<16x{QROW}xf16>
  // stage this wave's 16 query rows x {(8 - HOIST) * 16} channels once: {(8 - HOIST) // 2} chunks of 16 halves per lane
  %q_chunks = index.constant {8 - HOIST} : index
  %q_chunk_iters = index.constant {(8 - HOIST) // 2} : index
  scf.for %qi = [%c0 to %q_chunk_iters step %c1] {{
    %qid0 = index.mul %qi, %c32 : index
    %qid = index.add %qid0, %lane : index
    %qrow = index.div %qid, %q_chunks : index
    %qchunk0 = index.rem %qid, %q_chunks : index
    %qchunk = index.mul %qchunk0, %c16 : index
    %qrow_global0 = index.add %query_origin0, %qrow : index
    %qrow_global = index.assume %qrow_global0 [lt(%qrow_global0, %padded_tokens)] : index
    %qcol0 = index.add %head_base0, %qchunk : index
    %qcol1 = index.add %qcol0, %c{HOIST * 16} : index
    %qcol = index.assume %qcol1 [le(%qcol1, %q_col_limit), mul(%qcol1, 16)] : index
    %q_chunk = vector.load %q_view[%qrow_global, %qcol] : view<[%padded_tokens]x[%q_stride0]xf16> -> vector<16xf16>
    vector.store %q_chunk, %q_tile[%qrow, %qchunk] : vector<16xf16>, view<16x{QROW}xf16>
  }}
  kernel.barrier<workgroup> scope(subgroup) ordering(acq_rel)
"""
# the first HOIST Q fragments live in registers for the whole loop (each is 8 VGPRs)
for c in range(HOIST):
    K += (f"  %q_channel{c} = index.add %head_base0, %c{16*c} : index\n" if c else "  %q_channel0 = index.add %head_base0, %c0 : index\n")
    K += f"  %lhs{c} = vector.fragment.load<lhs> %q_view[%query_origin0, %q_channel{c}] shape [%m, %k_frag] : view<[%padded_tokens]x[%q_stride0]xf16> -> vector<16xf16>\n"
K += f"""  %final_max, %final_sum, %final0, %final1, %final2, %final3, %final4, %final5, %final6, %final7 = scf.for %key_tile = [%c0 to %key_tile_count step %c1](%row_max = %negative_vector : vector<8xf32>, %row_sum = %zero_vector : vector<8xf32>, %acc0 = %init : vector<8xf32>, %acc1 = %init : vector<8xf32>, %acc2 = %init : vector<8xf32>, %acc3 = %init : vector<8xf32>, %acc4 = %init : vector<8xf32>, %acc5 = %init : vector<8xf32>, %acc6 = %init : vector<8xf32>, %acc7 = %init : vector<8xf32>) -> ({", ".join(["vector<8xf32>"] * 10)}) {{
    %key_origin1 = index.mul %key_tile, %c{TILE} : index
    %key_origin0 = index.assume %key_origin1 [le(%key_origin1, %tile_origin_limit), mul(%key_origin1, {TILE})] : index
    // stage K and V tiles (rows past the sequence are zero headroom)
    %st_row0 = index.add %key_origin0, %st_key : index
    %st_row = index.assume %st_row0 [lt(%st_row0, %padded_tokens)] : index
    %k_chunk = vector.load %k_view[%st_row, %st_col] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
    %st_row_v0 = index.add %key_origin0, %st_key_v : index
    %st_row_v = index.assume %st_row_v0 [lt(%st_row_v0, %padded_tokens)] : index
    %v_chunk = vector.load %v_view[%st_row_v, %st_col_v] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
    vector.store %k_chunk, %k_tile[%st_key, %st_chunk] : vector<16xf16>, view<{TILE}x{ROW}xf16>
"""
if TILE == 32:
    K += f"""    %st_row_hi0 = index.add %st_row0, %c16 : index
    %st_row_hi = index.assume %st_row_hi0 [lt(%st_row_hi0, %padded_tokens)] : index
    %k_chunk_hi = vector.load %k_view[%st_row_hi, %st_col] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
    vector.store %k_chunk_hi, %k_tile[%st_key_hi, %st_chunk] : vector<16xf16>, view<{TILE}x{ROW}xf16>
    %st_row_v_hi0 = index.add %st_row_v0, %c16 : index
    %st_row_v_hi = index.assume %st_row_v_hi0 [lt(%st_row_v_hi0, %padded_tokens)] : index
    %v_chunk_hi = vector.load %v_view[%st_row_v_hi, %st_col_v] : view<[%padded_tokens]x[%kv_stride0]xf16> -> vector<16xf16>
"""
    for j in range(16):
        K += f"    %vf{j} = vector.extract %v_chunk_hi[{j}] : vector<16xf16> -> f16\n"
        K += f"    %vs{j} = index.add %st_chunk_v, %cj{j} : index\n"
        K += f"    view.store %vf{j}, %v_tile[%vs{j}, %st_key_v_hi] : f16, view<128x{VROW}xf16>\n"
K += f"""    %ve0 = vector.extract %v_chunk[0] : vector<16xf16> -> f16
    %vr0 = index.add %st_chunk_v, %cj0 : index
    view.store %ve0, %v_tile[%vr0, %st_key_v] : f16, view<128x{VROW}xf16>
    %ve1 = vector.extract %v_chunk[1] : vector<16xf16> -> f16
    %vr1 = index.add %st_chunk_v, %cj1 : index
    view.store %ve1, %v_tile[%vr1, %st_key_v] : f16, view<128x{VROW}xf16>
    %ve2 = vector.extract %v_chunk[2] : vector<16xf16> -> f16
    %vr2 = index.add %st_chunk_v, %cj2 : index
    view.store %ve2, %v_tile[%vr2, %st_key_v] : f16, view<128x{VROW}xf16>
    %ve3 = vector.extract %v_chunk[3] : vector<16xf16> -> f16
    %vr3 = index.add %st_chunk_v, %cj3 : index
    view.store %ve3, %v_tile[%vr3, %st_key_v] : f16, view<128x{VROW}xf16>
    %ve4 = vector.extract %v_chunk[4] : vector<16xf16> -> f16
    %vr4 = index.add %st_chunk_v, %cj4 : index
    view.store %ve4, %v_tile[%vr4, %st_key_v] : f16, view<128x{VROW}xf16>
    %ve5 = vector.extract %v_chunk[5] : vector<16xf16> -> f16
    %vr5 = index.add %st_chunk_v, %cj5 : index
    view.store %ve5, %v_tile[%vr5, %st_key_v] : f16, view<128x{VROW}xf16>
    %ve6 = vector.extract %v_chunk[6] : vector<16xf16> -> f16
    %vr6 = index.add %st_chunk_v, %cj6 : index
    view.store %ve6, %v_tile[%vr6, %st_key_v] : f16, view<128x{VROW}xf16>
    %ve7 = vector.extract %v_chunk[7] : vector<16xf16> -> f16
    %vr7 = index.add %st_chunk_v, %cj7 : index
    view.store %ve7, %v_tile[%vr7, %st_key_v] : f16, view<128x{VROW}xf16>
    %ve8 = vector.extract %v_chunk[8] : vector<16xf16> -> f16
    %vr8 = index.add %st_chunk_v, %cj8 : index
    view.store %ve8, %v_tile[%vr8, %st_key_v] : f16, view<128x{VROW}xf16>
    %ve9 = vector.extract %v_chunk[9] : vector<16xf16> -> f16
    %vr9 = index.add %st_chunk_v, %cj9 : index
    view.store %ve9, %v_tile[%vr9, %st_key_v] : f16, view<128x{VROW}xf16>
    %ve10 = vector.extract %v_chunk[10] : vector<16xf16> -> f16
    %vr10 = index.add %st_chunk_v, %cj10 : index
    view.store %ve10, %v_tile[%vr10, %st_key_v] : f16, view<128x{VROW}xf16>
    %ve11 = vector.extract %v_chunk[11] : vector<16xf16> -> f16
    %vr11 = index.add %st_chunk_v, %cj11 : index
    view.store %ve11, %v_tile[%vr11, %st_key_v] : f16, view<128x{VROW}xf16>
    %ve12 = vector.extract %v_chunk[12] : vector<16xf16> -> f16
    %vr12 = index.add %st_chunk_v, %cj12 : index
    view.store %ve12, %v_tile[%vr12, %st_key_v] : f16, view<128x{VROW}xf16>
    %ve13 = vector.extract %v_chunk[13] : vector<16xf16> -> f16
    %vr13 = index.add %st_chunk_v, %cj13 : index
    view.store %ve13, %v_tile[%vr13, %st_key_v] : f16, view<128x{VROW}xf16>
    %ve14 = vector.extract %v_chunk[14] : vector<16xf16> -> f16
    %vr14 = index.add %st_chunk_v, %cj14 : index
    view.store %ve14, %v_tile[%vr14, %st_key_v] : f16, view<128x{VROW}xf16>
    %ve15 = vector.extract %v_chunk[15] : vector<16xf16> -> f16
    %vr15 = index.add %st_chunk_v, %cj15 : index
    view.store %ve15, %v_tile[%vr15, %st_key_v] : f16, view<128x{VROW}xf16>
    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)
"""
K += f"""
    %local_key = index.add %key_origin0, %lane_column : index
    %key_valid = index.cmp ult, %local_key, %tokens0 : index
{"    %local_key_hi = index.add %local_key, %c16 : index" + chr(10) + "    %key_valid_hi = index.cmp ult, %local_key_hi, %tokens0 : index" + chr(10) if TILE == 32 else ""}"""
# scores: 8 channel steps, q fragment from global, k rhs from the LDS row (lane = key)
prev = "%init"
for c in range(8):
    if c >= HOIST and QROW:
        K += f"    %q_data{c} = vector.load %q_tile[%lane_column, %c{16*(c-HOIST)}] : view<16x{QROW}xf16> -> vector<16xf16>\n"
        K += f"    %lhs{c} = vector.fragment<lhs> %q_data{c} shape [%m, %k_frag] : vector<16xf16>\n"
    elif c >= HOIST:
        K += f"    %q_channel{c} = index.add %head_base0, %c{16*c} : index\n"
        K += f"    %lhs{c} = vector.fragment.load<lhs> %q_view[%query_origin0, %q_channel{c}] shape [%m, %k_frag] : view<[%padded_tokens]x[%q_stride0]xf16> -> vector<16xf16>\n"
    K += f"    %k_data{c} = vector.load %k_tile[%lane_column, %c{16*c}] : view<{TILE}x{ROW}xf16> -> vector<16xf16>\n" if c else f"    %k_data0 = vector.load %k_tile[%lane_column, %c0] : view<{TILE}x{ROW}xf16> -> vector<16xf16>\n"
    K += f"    %rhs{c} = vector.fragment<rhs> %k_data{c} shape [%k_frag, %n] : vector<16xf16>\n"
    out = "%raw_scores" if c == 7 else f"%qk{c}"
    K += f"    {out} = vector.mma %lhs{c}, %rhs{c}, {prev} : vector<16xf16>, vector<16xf16>, vector<8xf32>\n"
    prev = out
if TILE == 32:
    prev = "%init"
    for c in range(8):
        K += f"    %k_data_hi{c} = vector.load %k_tile[%lane_column_hi, %c{16*c}] : view<{TILE}x{ROW}xf16> -> vector<16xf16>\n" if c else f"    %k_data_hi0 = vector.load %k_tile[%lane_column_hi, %c0] : view<{TILE}x{ROW}xf16> -> vector<16xf16>\n"
        K += f"    %rhs_hi{c} = vector.fragment<rhs> %k_data_hi{c} shape [%k_frag, %n] : vector<16xf16>\n"
        out = "%raw_scores_hi" if c == 7 else f"%qk_hi{c}"
        K += f"    {out} = vector.mma %lhs{c}, %rhs_hi{c}, {prev} : vector<16xf16>, vector<16xf16>, vector<8xf32>\n"
        prev = out
K += """    %scaled0 = vector.mulf<reassoc|nnan|ninf|nsz|contract> %raw_scores, %scale_vector : vector<8xf32>
    %scaled = scf.if %key_valid -> (vector<8xf32>) {
      scf.yield %scaled0 : vector<8xf32>
    } else {
      scf.yield %negative_vector : vector<8xf32>
    }
"""
if TILE == 32:
    K += """    %scaled_hi0 = vector.mulf<reassoc|nnan|ninf|nsz|contract> %raw_scores_hi, %scale_vector : vector<8xf32>
    %scaled_hi = scf.if %key_valid_hi -> (vector<8xf32>) {
      scf.yield %scaled_hi0 : vector<8xf32>
    } else {
      scf.yield %negative_vector : vector<8xf32>
    }
    %pair_max = vector.maxnumf %scaled, %scaled_hi : vector<8xf32>
"""
TM = "%pair_max" if TILE == 32 else "%scaled"
K += f"""    // Tile row max across the 16 lanes of this lane's half: an xor butterfly over
    // offsets 1, 2, 4, 8 never crosses the halves, so no even/odd masking is needed.
    %sh1, %ok1 = kernel.subgroup.shuffle<xor> {TM}, %i32_1, %i32_32 : vector<8xf32>, i32, i32
    %tm1 = vector.maxnumf %scaled, %sh1 : vector<8xf32>
    %sh2, %ok2 = kernel.subgroup.shuffle<xor> %tm1, %i32_2, %i32_32 : vector<8xf32>, i32, i32
    %tm2 = vector.maxnumf %tm1, %sh2 : vector<8xf32>
    %sh4, %ok4 = kernel.subgroup.shuffle<xor> %tm2, %i32_4, %i32_32 : vector<8xf32>, i32, i32
    %tm4 = vector.maxnumf %tm2, %sh4 : vector<8xf32>
    %sh8, %ok8 = kernel.subgroup.shuffle<xor> %tm4, %i32_8, %i32_32 : vector<8xf32>, i32, i32
    %tm8 = vector.maxnumf %tm4, %sh8 : vector<8xf32>
    %next_max = vector.maxnumf %row_max, %tm8 : vector<8xf32>
    %delta = vector.subf<reassoc|nnan|ninf|nsz> %scaled, %next_max : vector<8xf32>
    // an invalid key's score is -inf, so its weight is exp(-inf) = 0 without a mask
    %weight = vector.expf<afn> %delta : vector<8xf32>
    // the row sum stays a per-lane partial (this lane's key column) until after the loop
    %old_delta = vector.subf<reassoc|nnan|ninf|nsz> %row_max, %next_max : vector<8xf32>
    %selected_old_scale = vector.expf<afn> %old_delta : vector<8xf32>
    %scaled_sum = vector.mulf<reassoc|nnan|ninf|nsz|contract> %row_sum, %selected_old_scale : vector<8xf32>
"""
if TILE == 32:
    K += """    %delta_hi = vector.subf<reassoc|nnan|ninf|nsz> %scaled_hi, %next_max : vector<8xf32>
    %weight_hi = vector.expf<afn> %delta_hi : vector<8xf32>
    %next_sum_lo = vector.addf<reassoc|nnan|ninf|nsz> %scaled_sum, %weight : vector<8xf32>
    %next_sum = vector.addf<reassoc|nnan|ninf|nsz> %next_sum_lo, %weight_hi : vector<8xf32>
    // the f32 weights become f16 lhs fragments through this wave's 1 KB scratch
    vector.fragment.store<result> %weight, %scratch_view[%c0, %c0] shape [%m, %n] : vector<8xf32>, view<16x16xf16>
    vector.fragment.store<result> %weight_hi, %scratch_view_hi[%c0, %c0] shape [%m, %n] : vector<8xf32>, view<16x16xf16>
    kernel.barrier<workgroup> scope(subgroup) ordering(acq_rel)
    %probability = vector.fragment.load<lhs> %scratch_view[%c0, %c0] shape [%m, %k_frag] : view<16x16xf16> -> vector<16xf16>
    %probability_hi = vector.fragment.load<lhs> %scratch_view_hi[%c0, %c0] shape [%m, %k_frag] : view<16x16xf16> -> vector<16xf16>
"""
else:
    K += """    %next_sum = vector.addf<reassoc|nnan|ninf|nsz> %scaled_sum, %weight : vector<8xf32>
    // the f32 weights become an f16 lhs through this wave's 512-byte scratch
    vector.fragment.store<result> %weight, %scratch_view[%c0, %c0] shape [%m, %n] : vector<8xf32>, view<16x16xf16>
    kernel.barrier<workgroup> scope(subgroup) ordering(acq_rel)
    %probability = vector.fragment.load<lhs> %scratch_view[%c0, %c0] shape [%m, %k_frag] : view<16x16xf16> -> vector<16xf16>
"""
for c in range(8):
    # B[k = key][n = channel]: lane n reads channel row 16c + n of the transposed tile, 16 keys contiguous
    K += f"    %vrow{c} = index.add %lane_column, %c{16*c} : index\n"
    K += f"    %v_data{c} = vector.load %v_tile[%vrow{c}, %c0] : view<128x{VROW}xf16> -> vector<16xf16>\n"
    K += f"    %v{c} = vector.fragment<rhs> %v_data{c} shape [%k_frag, %n] : vector<16xf16>\n"
for c in range(8):
    K += f"    %rescaled{c} = vector.mulf<reassoc|nnan|ninf|nsz|contract> %acc{c}, %selected_old_scale : vector<8xf32>\n"
if TILE == 32:
    for c in range(8):
        K += f"    %v_data_hi{c} = vector.load %v_tile[%vrow{c}, %c16] : view<128x{VROW}xf16> -> vector<16xf16>\n"
        K += f"    %v_hi{c} = vector.fragment<rhs> %v_data_hi{c} shape [%k_frag, %n] : vector<16xf16>\n"
    for c in range(8):
        K += f"    %mid{c} = vector.mma %probability, %v{c}, %rescaled{c} : vector<16xf16>, vector<16xf16>, vector<8xf32>\n"
    for c in range(8):
        K += f"    %next{c} = vector.mma %probability_hi, %v_hi{c}, %mid{c} : vector<16xf16>, vector<16xf16>, vector<8xf32>\n"
else:
    for c in range(8):
        K += f"    %next{c} = vector.mma %probability, %v{c}, %rescaled{c} : vector<16xf16>, vector<16xf16>, vector<8xf32>\n"
K += "    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)\n"
K += "    scf.yield %next_max, %next_sum, " + ", ".join(f"%next{c}" for c in range(8)) + " : " + ", ".join(["vector<8xf32>"] * 10) + "\n  }\n"
K += """  // the row sum: the per-lane partials of the 16 lanes of this half
  %fsh1, %fok1 = kernel.subgroup.shuffle<xor> %final_sum, %i32_1, %i32_32 : vector<8xf32>, i32, i32
  %fs1 = vector.addf<reassoc|nnan|ninf|nsz> %final_sum, %fsh1 : vector<8xf32>
  %fsh2, %fok2 = kernel.subgroup.shuffle<xor> %fs1, %i32_2, %i32_32 : vector<8xf32>, i32, i32
  %fs2 = vector.addf<reassoc|nnan|ninf|nsz> %fs1, %fsh2 : vector<8xf32>
  %fsh4, %fok4 = kernel.subgroup.shuffle<xor> %fs2, %i32_4, %i32_32 : vector<8xf32>, i32, i32
  %fs4 = vector.addf<reassoc|nnan|ninf|nsz> %fs2, %fsh4 : vector<8xf32>
  %fsh8, %fok8 = kernel.subgroup.shuffle<xor> %fs4, %i32_8, %i32_32 : vector<8xf32>, i32, i32
  %fs8 = vector.addf<reassoc|nnan|ninf|nsz> %fs4, %fsh8 : vector<8xf32>
  %selected_sum = vector.addf<reassoc|nnan|ninf|nsz> %fs8, %zero_vector : vector<8xf32>
"""
for c in range(8):
    K += f"  %out{c} = vector.divf<nnan|ninf|nsz|arcp> %final{c}, %selected_sum : vector<8xf32>\n"
K += """  // Publish one 16x16 fragment at a time through this wave's 1 KB stage: each lane
  // takes two vector4 slices, rows past the sequence dropped.
  %publish_row0 = index.div %lane, %c4 : index
  %publish_col_group = index.rem %lane, %c4 : index
  %publish_col = index.mul %publish_col_group, %c4 : index
  %publish_limit = index.sub %out_stride0, %c4 : index
  scf.for %fragment = [%c0 to %c8 step %c1] {
"""
sel = "%out0"
for j in range(1, 8):
    K += f"    %is{j} = index.cmp eq, %fragment, %c{j} : index\n    %pick{j} = scf.select %is{j}, %out{j}, {sel} : vector<8xf32>\n"
    sel = f"%pick{j}"
K += f"""    vector.fragment.store<result> {sel}, %result_view[%c0, %c0] shape [%m, %n] : vector<8xf32>, view<16x16xf32>
    kernel.barrier<workgroup> scope(subgroup) ordering(acq_rel)
    %frag_col = index.mul %fragment, %c16 : index
    %out_col_local = index.add %frag_col, %publish_col : index
    %out_column0 = index.add %head_base0, %out_col_local : index
    %out_column = index.assume %out_column0 [le(%out_column0, %publish_limit)] : index
    scf.for %half = [%c0 to %c2 step %c1] {{
      %row_offset = index.mul %half, %c8 : index
      %publish_row = index.add %publish_row0, %row_offset : index
      %local_row = index.add %query_origin0, %publish_row : index
      %present = index.cmp ult, %local_row, %tokens0 : index
      %in_range = index.cmp ult, %local_row, %token_count : index
      %writes = scalar.andi %present, %in_range : i1
      scf.if %writes {{
        %global_row = index.assume %local_row [lt(%local_row, %token_count)] : index
        %values = vector.load %result_view[%publish_row, %publish_col] : view<16x16xf32> -> vector<4xf32>
        %halves = vector.fptrunc %values : vector<4xf32> to vector<4xf16>
        vector.store %halves, %out_view[%global_row, %out_column] : vector<4xf16>, view<[%token_count]x[%out_stride0]xf16>
      }}
    }}
    kernel.barrier<workgroup> scope(subgroup) ordering(acq_rel)
  }}
  kernel.return
}}
"""
OUT.write_text(K)
print("wrote", OUT)
